### ISSUE TITLE
Prohibit the use of `Self` in non-init functions

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#1005]
The use of `Self` in non-init context might be harmful as sometimes it indicates that the function was meant to be marked with `#[init]`. It might make sense to gradually prohibit this pattern, e.g. give a deprecation warning in 4.2 and give a compilation error in 5.0.

Originally pointed out in https://github.com/near/near-sdk-rs/issues/972#issuecomment-1327720519.

**Comment by uint** [comment]
Once the deprecation warning is there, should we create a 5.0 milestone and attach this issue to it so that we don't forget to switch to the compilation error when it's time?

**Comment by uint** [comment]
Also, should passing a `Self` argument still be fine? The original motivation was about using it as the return type from what I see.

**Comment by itegulov** [comment]
We already have a tracking issue for 5.0: https://github.com/near/near-sdk-rs/issues/946

> Also, should passing a Self argument still be fine? The original motivation was about using it as the return type from what I see.

I personally think that all `Self` usage is potentially harmful in this context, but this is very opinionated
