### ISSUE TITLE
Refactor `info_extractor` to accumulate compilation errors

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#1006]
Currently `ItemImplInfo`, `ItemTraitInfo` (and potentially some others) return a compilation error as soon as they encounter a single method with a compilation error. Instead, they should accumulate such errors and combine them with [`syn::Error::combine`](https://docs.rs/syn/latest/syn/parse/struct.Error.html#method.combine). This would give a saner developer experience to the users whose contracts have multiple problems at once.

Originally pointed out in https://github.com/near/near-sdk-rs/pull/980#discussion_r1083681681.

**Comment by jaswinder6991** [comment]
I want to work on this.

**Comment by uint** [comment]
> I want to work on this.

@jaswinder6991 Sorry for the wait. Feel free to start a PR for this and reach out if you have any questions!

**Comment by jaswinder6991** [comment]
Hi @uint, opened this PR https://github.com/near/near-sdk-rs/pull/1065 to address this issue.
