### ISSUE TITLE
Question: K1 or R1 curve?

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-sdk-rs#1011]
In road map, NEAR will support `secp256r1` curve, but in `near_sdk`, a curve type named `SECP256K1` is in type `PublicKey`, any wrong here?

**Comment by agostbiro** [comment]
Hey, thanks for asking this question! We handle the curve type during parsing with the [`CurveType`](https://github.com/near/near-sdk-rs/blob/1f62a6883f3b99094267f33f9045954ab29af1d8/near-sdk/src/types/public_key.rs#L8) enum currently, so I think the implementation is reasonably future proof.

I'm closing the issue as complete, but please feel free to reopen if you have any concerns left.
