### ISSUE TITLE
cross-contract high level example doesn't work

### ISSUE THREAD

**Issue by bowenwang1996** [near/near-sdk-rs#102]
When following the cross contract high level example readme, at this step
```
near call cross_contract simple_call "{\"account_id\": \"status_message\", \"message\":\"bonjour\"}" --accountId=test_near --gas 1000000000000000
```
the call failed because it exceeds the prepaid gas, but I already give the maximum prepaid gas here (10^16).

**Comment by nearmax** [comment]
I am not able to reproduce it. Could you please post very specific steps to reproduce, including versions of everything that you are using?

**Comment by bowenwang1996** [comment]
See my fix here https://github.com/nearprotocol/near-bindgen/pull/103. The amount of gas passed as an argument to cross contract calls exceeds the maximum allowed prepaid gas.

**Comment by nearmax** [comment]
I am not able to reproduce it. To be able to reproduce I need to have specific steps with versions.

**Comment by bowenwang1996** [comment]
Use master for both nearcore and near-bindgen
Start local node for nearcore by `scripts/start_localnet.py --nodocker`.
Then create and deploy cross contract example:
```
near create_account cross_contract --masterAccount=test.near  --initialBalance 10000000
near deploy --accountId=cross_contract --wasmFile=../examples/cross-contract-high-level/res/cross_contract_high_level.wasm
```
Deploy status message contract
```
near call cross_contract deploy_status_message "{\"account_id\": \"status_message\", \"amount\":1000000000000000}" --accountId=test.near 
```
Do simple call
```
near call cross_contract simple_call "{\"account_id\": \"status_message\", \"message\":\"bonjour\"}" --accountId=test_near --gas 10000000000000000
```

**Comment by nearmax** [comment]
What is the near-shell version?

**Comment by bowenwang1996** [comment]
0.20.1
