### ISSUE TITLE
Running `cargo test`: module `export` is private 

### ISSUE THREAD

**Issue by Calcifer1001** [near/near-sdk-rs#1022]
I'm starting to use this. I'm using "3.2.0" as a dev-dependency.

After adding it, I've run `cargo build` and `cargo test`. The first one goes right, but the next one throws this

```
Compiling near-sdk-sim v3.2.0
error[E0603]: module `export` is private
   --> /home/calcifer/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-sim-3.2.0/src/outcome.rs:10:22
    |
10  | use near_sdk::serde::export::Formatter;
    |                      ^^^^^^ private module
    |
note: the module `export` is defined here
   --> /home/calcifer/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.159/src/lib.rs:322:5
    |
322 | use self::__private as export;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0603`.
error: could not compile `near-sdk-sim` due to previous error
```

I've checked those two files, trying to make it public adding pub and the error said in 322 dissapears but the other one remains. I understand I shouldn't be touching those files.

Thanks

**Comment by frol** [comment]
near-sdk-sim was deprecated quite long time ago in favor of [`near-workspaces`](https://github.com/near/workspaces-rs). near-sdk-rs 3.x is not supported anymore, so I can only recommend migrating to 4.x version.
