### ISSUE TITLE
Add test coverage for ABI generator

### ISSUE THREAD

**Issue by agostbiro** [near/near-sdk-rs#1031]
The [ABI generator implementation](https://github.com/near/near-sdk-rs/blob/e4cb471631c55fb8831403ffea12afc71030abc1/near-sdk-macros/src/core_impl/abi/abi_generator.rs) currently lacks test coverage which makes it difficult to refactor.

It'd be good to add test coverage similar to the [code generator.](https://github.com/near/near-sdk-rs/blob/e4cb471631c55fb8831403ffea12afc71030abc1/near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs#L30)

**Comment by itegulov** [comment]
I know it's not the same, but you might find cargo-near [integration tests](https://github.com/near/cargo-near/tree/main/integration-tests) useful. They basically test the whole ABI generation flow e2e, including SDK's ABI generator.

**Comment by agostbiro** [comment]
Great, thanks @itegulov !

**Comment by agostbiro** [comment]
I'm working on this.
