### ISSUE TITLE
Deprecate metadata module

### ISSUE THREAD

**Issue by agostbiro** [near/near-sdk-rs#1034]
As per @itegulov's [comment](https://github.com/near/near-sdk-rs/pull/1033#discussion_r1243042318) the `metadata` module should be deleted as it was replaced by `abi`. 

It should be deprecated first and then removed in 5.0.

**Comment by uint** [comment]
I took a look at this, but the only metadata-related symbol I see that's actually part of a public API is [the `metadata` macro](https://github.com/near/near-sdk-rs/blob/0075253c6d4b862817a8a7fe5105ac87dc223614/near-sdk-macros/src/lib.rs#L248-L277). This one already has a deprecation notice.

Am I missing something, or are we fine just deleting all this stuff in 5.0?

**Comment by itegulov** [comment]
You are right, we should be fine with just deleting it in 5.0
