### ISSUE TITLE
Deserialization error on contract call after rust update

### ISSUE THREAD

**Issue by alexvelicu** [near/near-sdk-rs#1035]
We have integrated a near contract in our development. 

When we compile / build / test / deploy the contract with 
cargo 1.66.1 (ad779e08b 2023-01-10)
rustup 1.25.1 (bb60b1e89 2022-07-12)
We can call the contract, execute view, no errors. 

After updating to rustup 1.26.0 (5af9b9484 2023-04-05)
Contract call returns Querying [object Object] failed: wasm execution failed with error: CompilationError(PrepareError(Deserialization))
Also on call to set values we get a receipt with 
```
"status": {
            "Failure": {
              "ActionError": {
                "index": 0,
                "kind": {
                  "FunctionCallError": {
                    "CompilationError": {
                      "PrepareError": "Deserialization"
                    }
                  }
                }
              }
            }
          }
```

This can be reproduced on 
https://github.com/near-examples/hello-near-rust/tree/main/contract
Any suggestions?

**Comment by agostbiro** [comment]
Hi @alexvelicu, thanks for reporting this! 

The error is an unfortunate consequence of `nearcore` [not yet supporting](https://github.com/near/nearcore/pull/9140) Rust 1.70. You can work around this limitation by using Rust 1.69. If you're using `rustup`, you can accomplish this automatically by placing a file called `rust-toolchain.toml` next to your `Cargo.toml` (or workspace root) with the following content:

```toml
[toolchain]
channel = "1.69"
```

I'll submit a PR in `hello-near-rust` to add this file.

**Comment by agostbiro** [comment]
Closing this as fixed as PR was merged to `hello-near-rust` https://github.com/near-examples/hello-near-rust/pull/6
