### ISSUE TITLE
Refactor bindgen snapshot unit tests to use `insta`

### ISSUE THREAD

**Issue by agostbiro** [near/near-sdk-rs#1038]
As @frol suggested in https://github.com/near/near-sdk-rs/pull/1036#discussion_r1246573665 we should refactor bindgen snapshot unit tests to use the [insta](https://github.com/mitsuhiko/insta) crate.

Unit tests that could benefit from this:

https://github.com/near/near-sdk-rs/blob/c39fba338c2fbbb2e4dd1487a4c6c978a780f89c/near-sdk-macros/src/core_impl/code_generator/item_impl_info.rs#L30

https://github.com/near/near-sdk-rs/blob/c39fba338c2fbbb2e4dd1487a4c6c978a780f89c/near-sdk-macros/src/core_impl/code_generator/item_trait_info.rs#L30

https://github.com/near/near-sdk-rs/blob/c39fba338c2fbbb2e4dd1487a4c6c978a780f89c/near-sdk-macros/src/core_impl/code_generator/ext.rs#L146

https://github.com/near/near-sdk-rs/blob/6887b411d2852fbcb41232264cc4178d09895d2b/near-sdk-macros/src/core_impl/abi/abi_generator.rs#L295

**Comment by jaswinder6991** [comment]
Hi @agostbiro, are you working on this issue? If not, I would like to try it out.

**Comment by iho** [comment]
@agostbiro @jaswinder6991 @frol  Do we have any progress? Can I take this task?

**Comment by frol** [comment]
@iho Please, go ahead! Take inspiration from [borsh-rs](https://github.com/near/borsh-rs) setup.
