### ISSUE TITLE
Introduce the ability to implement 3rd-party contract extensions.

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1041]
A continuation of https://github.com/near/near-sdk-rs/issues/422.

This should give an ability to wrap the functionality of an existing contract. Perhaps in a form of decorator, that needs to be discussed further to be properly fleshed-out. Perhaps some R&D is in order to figure out the most flexible and easy-to-use way.

Some context:
1. https://github.com/near/near-sdk-rs/issues/422#issuecomment-1614378589
2. An example from aforementioned issue:
```rust impl MatkladsFungibleToken for Contract { ... } 

#[near_bindgen::extensions]
impl Contract {
    // the user has to repeat the signature here specifcally for near_bindgen.
    // this is the bit we hardcode-away for known contracts
    fn ft_transfer(&mut self, receiver_id: ValidAccountId, amount: U128, memo: Option<String>); // note semicolon
} 
```

It's important to understand what's to be achieved by this, here are some questions/thoughts:
1. Do we want to wrap some of the existing methods effectively overriding bingdgen definitions generated for the original contract? 
2. Do we want to allow providing additional methods for the Contract? I'm guessing not, because that would eliminate the point of extending it in the first place. If yes - how, why?

**Comment by frol** [comment]
> Do we want to wrap some of the existing methods effectively overriding bingdgen definitions generated for the original contract?

@ruseinov Could you, please, elaborate more here? I don't understand the problem here.

> Do we want to allow providing additional methods for the Contract? I'm guessing not, because that would eliminate the point of extending it in the first place. If yes - how, why?

I am not sure if I understand you correctly here, but let me try to provide some hopefully relevant context.

Here is the code which is totally valid:

```rust
#[near_bindgen]
#[derive(BorshDeserialize, BorshSerialize)]
struct MyContract {}

#[near_bindgen]
impl MyContract {
    pub fn my_fn_one(&self) {}
}

#[near_bindgen]
impl MyContract {
    pub fn my_fn_in_other_impl_block(&self) {}
}

trait SomeNearStandardTrait {
    fn standard_fn(&self) {}
}

#[near_bindgen]
impl SomeNearStandardTrait for MyContract {
    fn standard_fn(&self) {}
}
```

All three functions will be exposed (`#[no_mangle] export "C"`) by near-sdk-rs. It already works in near-sdk-rs just fine, so I believe it already supports extensions, right?

**Comment by ruseinov** [comment]
TBH those old comments about extensions were a bit confusing, so I'm no longer sure what was the intention there. I suggest we close this and revisit as necessary.
