### ISSUE TITLE
Example doc for random seed

### ISSUE THREAD

**Issue by agostbiro** [near/near-sdk-rs#1051]
Add an example doc to

https://github.com/near/near-sdk-rs/blob/bb8a7f8c796e3dd2bd22b4066c97251288f7d84b/near-sdk/src/environment/env.rs#L261

The doc should showcase how to construct a struct that implements [SeedableRng](https://docs.rs/rand/latest/rand/trait.SeedableRng.html) from the `random_seed` and uses [Rng::gen_range](https://docs.rs/rand/latest/rand/trait.Rng.html#method.gen_range) to get a random value in a range with the seed.

The doc should also contain a warning that the random seed should not be used as input to cryptographic primitives.

**Comment by frol** [comment]
> The doc should also contain a warning that the random seed should not be used as input to cryptographic primitives.

[Random seed in NEAR is quite well-thought](https://near.org/blog/randomness-in-blockchain-protocols), so it can be used for security-critical needs, but the public nature of the blockchain might be the blocker anyway. So I would not add that warning.

**Comment by agostbiro** [comment]
Thanks for raising this @frol , the issue warrants more discussion, so I wrote it up in detail.

As explained in the [paper,](https://pages.near.org/downloads/NearRandomnessBeacon.pdf) the goal of the NEAR randomness beacon is twofold:

> 1. Unpredictable. No participant should be able to predict the resulting
> number or reason about any properties of it before the number is created.
> 2. Unbiasable. No participant should be able to influence the resulting
> number in any way.

These goals work well (with some [caveats](https://docs.near.org/develop/contracts/security/random)) for use cases such as on-chain betting where the quality of the randomness only matters during the execution of the transaction by the block producer.

Many cryptographic primitives such as encryption algorithms rely on random values as inputs. These random values are generated with cryptographically secure pseudorandom number generators (CSPRNG). The requirement on CSPRNGs is that their output should be undistinguishable from a truly random distribution by an adversary. 

CSPRNGs are called pseudorandom, because their outputs depend on a seed value. If the attacker learns about this seed value, they can distinguish the CSPRNG output from a random distribution, so the security of the CSPRNG and all the cryptographic primitives that depend on it is broken. 

Poor seeding of a CSPRNG is a common source of vulnerabilities. The best practice to avoid this is to use the secure random number generator API exposed by the OS (e.g. [`getrandom`](https://man7.org/linux/man-pages/man2/getrandom.2.html) on Linux) to seed the CSPRNG used by the application. The expectation with values returned from the OS API is that they cannot be recovered once they're dropped from memory by the application.

My understanding is that the value returned in `near_sdk::env::random_seed` is the same within a block, it's known by the producer, and we should assume that the seed values are recoverable for historical blocks. (I don't understand well enough how it works to give a solution for all blocks, but trivially, it could be logged by a contract.) This means that if `near_sdk::env::random_seed` is used to seed a CSPRNG, all the outputs of the CSPRNG will be recoverable by an adversary. This is very different from the expectation on seeds for CSPRNGs which is why I thought it appropriate to issue a warning that the random seed should not be used as input to cryptographic primitives.

To give a concrete example of how things could wrong, consider an NFT where some secret property of the NFT is only revealed to the owner, but the owner can selectively reveal it to other blockchain users. A naive implementation could solve this by generating a data encryption key (DEK) within the NFT contract using a CSPRNG seeded with `near_sdk::env::random_seed`, then encrypt the secret property with the DEK, then encrypt the DEK with the public key of the owner and then store the encrypted DEK in the contract. The owner could then retrieve the encrypted DEK and encrypt it with the public key of another user and store the newly encrypted DEK in the contract to let the other user access the secret property.

Now this scheme could be trivially broken, since the block producer knows the seed value, other contracts executed within the same block also know the seed value and historic seed values are recoverable. But if you turned the smart contract into a Linux program and replaced the call to `near_sdk::env::random_seed` with a call to `getrandom`, the Linux program would be secure. This is why I think some users might be surprised by how `near_sdk::env::random_seed` behaves.

Question to me is how shall we best communicate the difference? Maybe we could explain that seed values are public and this can be a problem for use in cryptographic primitives?

**Comment by frol** [comment]
> Maybe we could explain that seed values are public and this can be a problem for use in cryptographic primitives?

@agostbiro I feel this is the main blocker and not the lack of a cryptographically secure random generator property.

**Comment by frol** [comment]
there should also be a link to https://docs.near.org/develop/contracts/security/random

Consider mentioning https://lib.rs/crates/near-rng (I did not look into the code, but from the docs it is promissing)

https://stackoverflow.com/questions/71092791/how-to-select-a-random-key-from-an-unorderedmap-in-near-rust-sdk
