### ISSUE TITLE
Add a macro for building account IDs

### ISSUE THREAD

**Issue by uint** [near/near-sdk-rs#1061]
First mentioned in #944.

The big selling point of the macro would be verifying ID correctness statically when possible.

**Comment by frol** [comment]
> The big selling point of the macro would be verifying ID correctness statically when possible.

I wonder if `const fn` would be capable to verify ID correctness for `&str` (`&AccountIdRef`). It would be much better than adding one more way to construct account ID.

**Comment by uint** [comment]
> I wonder if const fn would be capable to verify ID correctness

I looked into it a bit, but it doesn't seem like it's possible to iterate over string characters in a constant context currently.

**Comment by frol** [comment]
@uint We figured it out: https://github.com/near/near-account-id-rs/pull/12
