### ISSUE TITLE
Suggestion for upgrading `borsh` dependency to `0.10` in the next release.

### ISSUE THREAD

**Issue by riversyang** [near/near-sdk-rs#1083]
Hi there, Octopus Network is working on [near-ibc](https://github.com/octopus-network/near-ibc) which will enable IBC based cross-chain bridge on NEAR protocol. 

We plan to integrate the latest [ibc-rs](https://github.com/cosmos/ibc-rs). The latest version of `ibc-rs` to be released has a dependency on `borsh 0.10` (due to the requirements of other dependencies, see [this issue](https://github.com/cosmos/ibc-rs/issues/695)), but the current release version (4.1.1) of `near-sdk-rs` has a dependency on `borsh 0.9`.

I looked at the source code of the latest `near-sdk-rs`, and I found that the `borsh` dependency is still `0.9`. So this will affect the release of the `near-ibc` project.

I'm wondering why this dependency is still not upgraded in `near-sdk-rs`, is there any special consideration? If not, we would like to see `borsh` upgraded to `0.10` in the next release of `near-sdk-rs`.

BTW. We also expect the `env::ed25519_verify` function to be available in the next release of `near-sdk-rs`, which will help us reduce the gas consumption of signature verification in tendermint light client in `near-ibc` contract, which is also very important for `near-ibc`.

Thank you!

**Comment by frol** [comment]
@riversyang Thanks for flagging it! There is a major push to borsh 1.0, and we already have a draft PR #1075 that checks that 1.0-alpha works as expected!

**Comment by frol** [comment]
#1075 upgraded borsh to 1.0
