### ISSUE TITLE
Bump rustc version.

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1087]
We are getting CI errors due to an old rustc version. Shall we bump it to latest stable? Or at least `1.70`?

https://github.com/near/near-sdk-rs/actions/runs/6353767202/job/17259031146?pr=1077

**Comment by frol** [comment]
There were some issues with Rustc 1.70+ producing wasm files that were not compatible with nearcore runtime: https://github.com/near/nearcore/issues/9143 - it was resolved on nearcore side, but we have not yet cut the releases of near-workspace-rs and sandbox to pick up that newer version, so we cannot bump the version just yet.

**Comment by frol** [comment]
I don't think we need to bump the version just yet, so I am closing this issue
