### ISSUE TITLE
Support Source Metadata out of the box

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#1102]
We need to implement https://github.com/near/NEPs/blob/master/neps/nep-0330.md into near-sdk-rs, so every contract built with near-sdk-rs would automatically get `contract_source_metadata` method exposed with the information populated from Cargo.toml and consider how to register near-contract-standards as available standards.

**Comment by shariffdev** [comment]
Hey @frol assign me to this and I will take a look at this, thanks!

**Comment by shariffdev** [comment]
I want to go about it by having `contract_source_metadata` created implicitly, as suggested using info from Cargo.toml, if not initialised by the contract author.

It can also be created explicitly if the metadata details are provided by a macro. The explicit implementation will be along the lines of:

```rust
use near_sdk::borsh::{self, BorshDeserialize, BorshSerialize};
use near_sdk::near_bindgen;

#[derive(Default, BorshSerialize, BorshDeserialize)]
#[near_bindgen(contract_metadata(
    version = "39f2d2646f2f60e18ab53337501370dc02a5661c",
    link = "https://github.com/near-examples/nft-tutorial",
    standards = [
        {standard = "nep330", version = "1.1.0"},
        {standard = "nep171", version = "1.0.0"},
        {standard = "nep177", version = "2.0.0"},
    ]
))]
#[near_bindgen]
stuct Contract {}
```

**Comment by frol** [comment]
@shariffdev The proposed solution sounds good to me. I would only consider if there is really a need for duplicative `#[near_bindgen]` - I don't see a good reason for it.

**Comment by shariffdev** [comment]
Sure, I can work around not making it duplicative.

**Comment by shariffdev** [comment]
The standards input changed to this to play well with the parser
```rust
#[near_bindgen(contract_metadata(
    version = "39f2d2646f2f60e18ab53337501370dc02a5661c",
    link = "https://github.com/near-examples/nft-tutorial",
    standard(standard = "nep330", version = "1.1.0"),
    standard(standard = "nep171", version = "1.0.0"),
    standard(standard = "nep177", version = "2.0.0"),
))]
stuct Contract {}
```
