### ISSUE TITLE
refactor: Replace internal account id type with the near-account-id crate

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#1105]
Replace copy-pasta code: https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/types/account_id.rs with https://crates.io/crates/near-account-id/1.0.0-alpha.1 (1.0.0-alpha.2 or newer)

**Comment by Asymtode712** [comment]
I want to work on it. Please assign me

**Comment by frol** [comment]
@Asymtode712 Please, go ahead!

**Comment by Asymtode712** [comment]
@frol Please review my PR and suggests if there are some changes to be made.

**Comment by frol** [comment]
@Asymtode712 Any updates? Do you plan to keep working on it?

**Comment by ruseinov** [comment]
@frol This seems already done.
