### ISSUE TITLE
Re-exported packages cleanup. 

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1112]
Make sure we're using re-exported packages from `near-sdk` as opposed to adding those directly to `Cargo.toml`.

Some good examples of that include `serde` package in `near-contract-standards`.

**Comment by frol** [comment]
I asked @iho to work in this one

**Comment by frol** [comment]
@PolyProgrammist I don't see any other places to be honest. Thanks for checking and fixing the remaining ones
