### ISSUE TITLE
The `PanicOnDefault` derive macro doesn't support generics

### ISSUE THREAD

**Issue by gnull** [near/near-sdk-rs#1116]
https://github.com/near/near-sdk-rs/blob/00226858199419aaa8c99f756bd192851666fb36/near-sdk-macros/src/lib.rs#L456C8-L456C8

Doing

```rust
#[derive(PanicOnDefault)]
struct Foo<T> {
  field: T,
}
```

fails with an error because `PanicOnDefault` derive macro doesn't support structs that have generic parameters `<T>`.

Seems like an unnecessary restriction. Could you please implement support for generics here?

Ivan

**Comment by frol** [comment]
Indeed, totally unnecessary restriction. It is not a high priority item and it is well-defined, so I will mark it as good first issue and keep in the backlog.

**Comment by funkyenough** [comment]
Hi I am new to Near and would like to pick this up as my first issue.

**Comment by kavink98** [comment]
Is this issue still open?

**Comment by frol** [comment]
@kavink98 Yes, it is still open. Feel free to pick it up

**Comment by g4titanx** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/near-sdk-rs).

### My background and how it can be leveraged
hi, I would love to work on this

**Comment by frol** [comment]
On a second thought, I believe that generic State struct doesn’t really make sense and doesn’t work in general. While DefaultOrPanic can be used outside of that scope, I don’t see how that can be useful.

@gnull Could you share your usecase?

In either case, the workaround is extremely simple - implement Default trait for the struct manually and panic there. Thus, this should remain low priority or even be closed unless a strong usecase is presented

**Comment by frol** [comment]
I have also tested the generic type parameter for contract state struct and we already have a clear error message there that it is not supported, which is understandable:

<img width="588" alt="image" src="https://github.com/user-attachments/assets/229331d6-d876-4457-831d-244c3709176a">
