### ISSUE TITLE
Investigate automating ABI tests for internal implementations

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1124]
It would be nice to see failures when we introduce some more codegen for `near_bindgen` that does not take care of the ABI, similar to the PR mentioned below.

_Originally posted by @ruseinov in https://github.com/near/near-sdk-rs/pull/1118#discussion_r1431325142_

**Comment by shariffdev** [comment]
Added https://github.com/shariffdev/near-sdk-rs/commit/20987c89e4047f3360c463a1d45f2f2926bc6dd3, haven't placed it as a PR as it's incomplete(run on CI vs not on CI).
We use the `cargo-near` tool to generate the abi spec file. Would we want to include that on the CI just for this test to run automatically?

**Comment by frol** [comment]
@shariffdev I fear that use of `cargo-near` may lead to circular dependencies. `cargo-near` does not do much, it just uses abi feature flag on near-sdk-rs, so you should be able to replicate that without cargo-near
