### ISSUE TITLE
Compilation error on fresh Cargo.toml that depends on near-sdk-rs 5.0.0-alpha.1

### ISSUE THREAD

**Issue by fadeevab** [near/near-sdk-rs#1129]
I tried to compile my project with `near-sdk-rs` `5.0.0-alpha.1` because of this issue https://github.com/near/near-sdk-rs/issues/1119, however, build fails with the errors:
```
error: proc-macro derive panicked
 --> src/main.rs
  |
6 | #[derive(BorshSerialize, BorshDeserialize)]
  |          ^^^^^^^^^^^^^^
  |
  = help: message: called `Result::unwrap()` on an `Err` value: Could not find `borsh` in `dependencies` or `dev-dependencies` in `/home/xxxx/yyyyy/Cargo.toml`!
```

**Comment by frol** [comment]
Given that we re-export borsh from near-sdk, you need to hint it to borsh:

https://github.com/near/near-sdk-rs/blob/13430592a7be246dd5a29439791f4081e0107ff3/examples/adder/src/lib.rs#L6
