### ISSUE TITLE
fail to build contract under near-sdk 5.0.0 and cargo near 0.6.1

### ISSUE THREAD

**Issue by WuDi329** [near/near-sdk-rs#1153]
The build instructions are as follows：
![image](https://github.com/near/near-sdk-rs/assets/55496466/d147baed-b13e-4a0c-9aa6-cdde305a277e)
this is cargo.toml
![image](https://github.com/near/near-sdk-rs/assets/55496466/29fe0674-8795-4345-9a57-267a61b6d162)
These are the problems I have when compiling
![image](https://github.com/near/near-sdk-rs/assets/55496466/5e45db96-c85c-4cf1-bc5f-ed091c3f7869)
I am confused as to why near_abi and schemars cannot be found during compilation. I have even set their versions in cargo.toml.

**Comment by frol** [comment]
@WuDi329 Just remove the explicit `abi` feature enablement from Cargo.toml:

```toml
near-sdk = "5.0.0"
```

I will investigate what exactly breaks there when you enable it explicitly, but cargo-near will enable it automatically.

**Comment by WuDi329** [comment]
> Just remove the explicit `abi` feature enablement from Cargo.toml:
> 
> ```toml
> near-sdk = "5.0.0"
> ```

Thanks for your reply, I've modified cargo.toml as you said, but it doesn't seem to have changed the build result.

![image](https://github.com/near/near-sdk-rs/assets/55496466/855e7fee-035d-410f-a618-361b58d90c0a)

**Comment by frol** [comment]
https://github.com/near/near-sdk-rs/blob/9bb16c2d08d522baf52ddd126e3fe0f01386f2ca/near-sdk/Cargo.toml#L40-L42

Just for the context, I remembered why it fails to compile, we don't even include schemars / near-abi for Wasm target to avoid unexpected dependencies. ABI is generated and extracted ahead of time as a separate step that compiles the code to the host platform first.

@WuDi329 I cannot reproduce your compilation error. Also, remove near-abi and schemars, prefer using `near_sdk::borsh` over direct dependency on borsh, and MOST IMPORTANTLY, remove `rand` and `getrandom` from your dependencies (you can use them in dev-dependencies), they won't work in Wasm environment; use [near-rng](https://docs.rs/near-rng/latest/near_rng/struct.Rng.html) if you need random numbers inside the contract.

**Comment by WuDi329** [comment]
> Also, remove near-abi and schemars, prefer using `near_sdk::borsh` over direct dependency on borsh, and MOST IMPORTANTLY, remove `rand` and `getrandom` from your dependencies (you can use them only in dev-dependencies, for tests), they won't work in Wasm environment; use [near-rng](https://docs.rs/near-rng/latest/near_rng/struct.Rng.html) if you need random numbers inside the contract.

Thank you, @frol ! I have seen your suggestion and removed near-abi,schemars etc. from cargo.toml, I will also use near_sdk::borsh instead of borsh, use near-rng instead of rand and getrandom.

> https://github.com/near/near-sdk-rs/blob/9bb16c2d08d522baf52ddd126e3fe0f01386f2ca/near-sdk/Cargo.toml#L40-L42
> 
> Just for the context, I remembered why it fails to compile, we don't even include schemars / near-abi for Wasm target to avoid unexpected dependencies. ABI is generated and extracted ahead of time as a separate step that compiles the code to the host platform first.

I have seen the cargo.toml in the near-sdk, so does this mean that when my compilation target is wasm32, it will fail due to missing near_abi and schemars? I don't know if my understanding is correct, because I am a newbie in rust. If you have any questions, please point them out. Now do you have any suggestions to solve this problem?

**Comment by frol** [comment]
> Now do you have any suggestions to solve this problem?

I cannot reproduce your error, so I cannot help you unless you provide a minimal reproducible example. Try creating a new project (`cargo near new`) and copy Cargo.toml from there.

**Comment by WuDi329** [comment]
@frol I'm sorry that I was busy with other work some time ago, and now I hope to get your help in solving this problem.
>  Try creating a new project (cargo near new) and copy Cargo.toml from there.

I've created a minimal repository like this. https://github.com/WuDi329/minimal-near, I wrote what I tried in the readme. This minimal comes from the default project created by cargo near new. I added a function in contract, get_round_status, which will return a type I defined in demo-dependency, nothing more.

### But when I try to run cargo near abi, it reports the following error：
![image](https://github.com/near/near-sdk-rs/assets/55496466/fd966855-66c3-4d7f-8d7d-00899218796f)
In fact, I have added abi to the cargo.toml of dependency-demo.
![image](https://github.com/near/near-sdk-rs/assets/55496466/fca02859-ef22-4840-a8c2-ca1afecbea86)

### When I run cargo build --target wasm32-unknown-unknown directly, I get an error like this
![image](https://github.com/near/near-sdk-rs/assets/55496466/4e8d0070-1a61-4ab3-9a99-1c676db1b60e)

I guess you might ask why I put that variable in an additional dependent library, it's because the system I want to implement includes both on-chain and off-chain parts, and they all rely on the same data structure definition, but Their functions do not go together.

Do you have any suggestions? If you have any questions, you are welcome to tell me.

**Comment by frol** [comment]
@WuDi329 here is the fix: https://github.com/WuDi329/minimal-near/pull/1
