### ISSUE TITLE
Can't found collections in nearsdk

### ISSUE THREAD

**Issue by pichtranst123** [near/near-sdk-rs#1154]
When I used near-sdk 5.0.0, import crate in Cargo.toml near-sdk = "5.0.0" and got this error below:
`use near_sdk::collections => collections could not find in near_sdk`
Please suggest another way to using HashMap in near-sdk

**Comment by encody** [comment]
You need to enable the `"legacy"` feature now. See the notes in [the changelog](https://github.com/near/near-sdk-rs/blob/e22f74ea9f6a0be8fe030a9225716eab811116ea/CHANGELOG.md#500---2024-02-21).
