### ISSUE TITLE
`near-contract-standards/non-fungible-token`: NEAR values instead of yoctoNEAR are returned in a storage management error message

### ISSUE THREAD

**Issue by yandrushchak** [near/near-sdk-rs#1160]
Package version: `near-contract-standards = "5.0.0"`

**Steps to reproduce:**

1. Implement standard NFT contract from `near-contract-standards`, e.g. example from this repo - https://github.com/near/near-sdk-rs/tree/near-sdk-v5.0.0/examples/non-fungible-token.
2. Call method that requires attached storage with not enough deposit, e.g. `nft_approve`.

**Actual result**: `Smart contract panicked: Must attach <0.001 NEAR yoctoNEAR to cover storage`
**Expected result**: Message with proper amount of yoctoNEAR is returned.

**Additional info:**

This happens because panic message uses `NearToken`, which is formatted as NEAR amount - https://github.com/near/near-sdk-rs/blob/near-sdk-v5.0.0/near-contract-standards/src/non_fungible_token/utils.rs#L36.

**Comment by nicosanc** [comment]
> @yandrushchak Good catch!
> 
> Let's extract the [exact-display implementation from near-cli-rs](https://github.com/near/near-cli-rs/blob/7fca81bb5544b40743290d3a951c1f1ff31a95d9/src/types/near_token.rs#L18-L35) into `NearToken::exact_amount_display(&self)` method in https://github.com/near/near-token-rs and use it here as:
> 
> ```rust
> format!("Must attach {} yoctoNEAR to cover storage", required_cost.exact_amount_display())
> ```
> 
> Would you have time to contribute the fix? I am happy to help you

Is the method "NearToken::exact_amount_display(&self)" the same as the Display implementation shown in src/trait_impls/display.rs? I'm having trouble localizing that specific method in near-token-rs

**Comment by frol** [comment]
@nicosanc The point is to copy/move the implementation from https://github.com/near/near-cli-rs/blob/7fca81bb5544b40743290d3a951c1f1ff31a95d9/src/types/near_token.rs#L18-L35 to https://github.com/near/near-token-rs, and then use it here:

https://github.com/near/near-sdk-rs/blob/9bb16c2d08d522baf52ddd126e3fe0f01386f2ca/near-contract-standards/src/non_fungible_token/utils.rs#L36

**Comment by lauchaves** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/near-sdk-rs).

### My background and how it can be leveraged
Hey! I'm Lau Chaves, and I would like to contribute to this issue!

I have over 5 years of experience working with JavaScript, React, TypeScript, ruby... I’m excited to dive deeper into smart contracts, and this looks like a fantastic chance to learn a bit more!

### How I plan on tackling this issue
Based on the intrucstions mentioned on the comments above and the issue itself,  Here’s how I would approach the problem:

- Extract Code: Obtain the exact_amount_display method from `near-cli-rs`and add it to the `NearToken` struct in `near-token-rs`.
- Update Panic Message: Modify the panic message in the non_fungible_token contract to use:
`format!("Must attach {} to cover storage", required_cost.exact_amount_display())`
- Test: Ensure that the updated message now correctly shows the required amount in `yoctoNEAR`.

**Comment by frol** [comment]
@TropicalDog17 I think this is too simple for Rust devs, and given that you already have another issue assigned to, I decided to give @lauchaves a chance here.

@lauchaves Please, go ahead!

**Comment by lauchaves** [comment]
@frol awesome, thank you! I'll get started on it right away.

**Comment by lauchaves** [comment]
Hey @frol would you mind taking a look at this [near-token pull request](https://github.com/near/near-token-rs/pull/9) ?
