### ISSUE TITLE
Consider adding `#[payable]` to Rust docs

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#1177]
I noticed that I couldn't find "payable" in the Rust docs site.

https://docs.rs/near-sdk/latest/near_sdk/index.html?search=payable

I thought `#[payable]` was removed, checked if it was in the `near-sdk-macros` crate. I'm not positive of how that macro works, but it seems like it might be important to index in the appropriate crate's documentation so a search could find it.

I've played with the Rust docs a bit and it can be very particular ;) Maybe we can start with anything that gets the content indexed for search, even if it doesn't fit as nicely as we'd like.

**Comment by frol** [comment]
Getting macro attributes documented is really tricky, but this is indeed one of the most important aspects of near-sdk.

**Comment by frol** [comment]
Resolved in #1185
