### ISSUE TITLE
Conflict of `near-sdk` with `k256` crypto library

### ISSUE THREAD

**Issue by kushkamisha** [near/near-sdk-rs#1179]
Hi,

I'm trying to use a Rust `k256` library along with `near-sdk` and got a malfunctioning contract that builds, deploys, but is not able to execute any functions. For the MVP example of the issue, please see [this GitHub repo](https://github.com/kushkamisha/k256-near-conflict), where [this is the commit](https://github.com/kushkamisha/k256-near-conflict/commit/66ea6372c135308b43c1b3679920356597aaca69) without `k256` import, and [this one](https://github.com/kushkamisha/k256-near-conflict/commit/4c5e65389ee25a1ae34c4b366ad5bf7e4f8a8240) with `k256` import. In the first scenario I'm able to easily deploy the contract and call a `get_greeting` function, whereas in the second (with just one import line added) the contract returns an error for a `get_greeting` call:

```bash
Here is your console command if you need to script it or re-run:
    near contract call-function as-read-only lucky-fish.testnet get_greeting text-args '' network-config testnet now

Error: 
   0: Failed to fetch query for view method: 'get_greeting' (contract <lucky-fish.testnet> on network <testnet>)
   1: Failed to make a view-function call
   2: handler error: [Function call returned an error: wasm execution failed with error: CompilationError(PrepareError(Instantiate))]

Location:
   src/common.rs:1923
```

I'm pretty confused why one import line of `use k256::ecdsa::{RecoveryId, Signature, VerifyingKey};` makes the contract to malfunction. Any ideas?

**Comment by PiVortex** [comment]
I'm not familiar with this library but this library is importing many methods (over 700), which are likely interfering, and it is probably a very large WASM file https://testnet.nearblocks.io/address/lucky-fish.testnet

Just to let you know that NEAR is EDDSA, not ECDSA (unless you are building some cool multichain stuff :) )

**Comment by kushkamisha** [comment]
@PiVortex Unfortunately, I need exactly the ECDSA functionality as I want to verify Ethereum signatures in the Near contract. So ‘k256’ seems to be the exact library I’m looking for, except for the issue I’m mentioning.

I was also trying to find any other library for Rust that can do that and is compatible with the wasm3-undefined-undefined target. As for now I cannot find anything - maybe will need to implement one

**Comment by PiVortex** [comment]
Could you try bringing up the problem in these groups, please 
[Tooling group](https://t.me/NEAR_Tools_Community_Group) for near_sdk_rs issues
[Chain abstraction group](https://t.me/+RXYjlPob_XM5N2Ex) for libraries verifying ECDSA signatures

**Comment by kushkamisha** [comment]
@PiVortex I've just checked and it shouldn't be a size issue. As:
1. Contract without k256 -> [116 kb](https://explorer.testnet.near.org/accounts/hideous-bread.testnet)
2. Contract with import k256 -> [269 kb](https://explorer.testnet.near.org/accounts/lucky-fish.testnet)
3. Near contract size limit-> [4.19 mb](https://docs.near.org/build/smart-contracts/anatomy/basics)

Maybe you have other suggestions?

**Comment by kushkamisha** [comment]
Update on this issue. It seems that the current k256 library using some of the dependencies with versions that are not officially released. To resolve the problem I had to manually build k256 locally from their GitHub repo and remove most of dependencies and features I don't need. Then, moved this reduced k256 folder into my project and included as a local dependency. 

P.S. That's why it's bad when you release a new version of the package that relies on some nightly changes in other packages
