### ISSUE TITLE
near_sdk::store::LazyOption

### ISSUE THREAD

**Issue by gucoi** [near/near-sdk-rs#1184]
### What talent are you looking for?

None

### What you need to be done?

near_sdk version 5.1.0 and feature is unstable version, but it happen some bug when i use the lazyOption 

│ error[E0432]: unresolved import `near_sdk::store::LazyOption`
 │   --> src/lib.rs:1:5
 │    |
 │ 1  | use near_sdk::store::LazyOption;
 │    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `LazyOption` in `store`
 │    |
 │ note: found an item that was configured out
 │   --> /Users//.cargo/registry/src/rsproxy.cn-8f6827c7af8/near-sdk-5.1.0/src/store/mod.rs:69:22
 │    |
 │ 69 | pub use lazy_option::LazyOption;
 │    |                      ^^^^^^^^^^
 │    = note: the item is gated behind the `unstable` feature
 │
 │ For more information about this error, try `rustc --explain E0432`.
 │ error: could not compile `factory_example` (lib) due to 1 previous error
Error: Error { repr: Custom { kind: Io, error: `cd "/Users//near/near_factory_example" && RUSTFLAGS="-C link-arg=-s" "/Users//.rustup/toolchains/stable-x86_64-apple-darwin/bin/cargo" "build" "--message-format=json-render-diagnostics" "--target" "wasm32-unknown-unknown" "--release" "--color" "always"` failed with exit code: Some(101) } }

### Currency

USDC.e

### KYC

- [ ] Use KYC Verification

**Comment by frol** [comment]
The error clearly states that you need to enable `unstable` feature while it is hidden under that feature flag. Subscribe to #1199 to follow the stabilization effort
