### ISSUE TITLE
`log!("{x}")` treats input as a raw string

### ISSUE THREAD

**Issue by Sliman4** [near/near-sdk-rs#1188]
When you write `log!("{x}")`, it outputs `{x}` literally instead of the value of variable `x` because `log!` is implemented differently if it has only 1 expression:

https://github.com/near/near-sdk-rs/blob/8a908c30ce43fbf1b1866486668a647fbc28b5bd/near-sdk/src/utils/mod.rs#L36-L43

`log!("{x}",)` (with a trailing comma) bypasses this, but I think it would be nice to maintain 100% compatibility with `std::fmt`.

If a string allocation makes a significant difference for some contract, is there a reason why they can't just use `env::log_str` directly? This call will also explicitly mark that this log outputs a lot of data and should not be changed to something that allocates, to avoid situations when at some point you add one `{}` to the log, and gas usage skyrockets for an unknown reason.

**Comment by frol** [comment]
@Sliman4 The macro was implemented before string interpolation became a thing in Rust (stable). I agree with your reasoning. Would you like to prepare a PR?
