### ISSUE TITLE
Tests for promises and cross contract examples

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#119]
Currently it's unclear how to actually test promises (starting from Transfer, Staking to calls for other contracts). Current examples don't provide any examples of such tests either.

**Comment by itegulov** [comment]
[cross-contract](https://github.com/near/near-sdk-rs/tree/master/examples/cross-contract-calls) and [factory-contract](https://github.com/near/near-sdk-rs/tree/master/examples/factory-contract) examples show how to tests promises

**Comment by migom6** [comment]
These examples are using workspaces lib, I can't find an example with the pure rust runtime test env. While making the cross contract calls, it return a Promise and I am clueless what to do with that.

**Comment by austinabell** [comment]
> These examples are using workspaces lib, I can't find an example with the pure rust runtime test env. While making the cross contract calls, it return a Promise and I am clueless what to do with that.

There is no way to simulate this within unit tests, the best you can do is checking that the async call was scheduled correctly with https://docs.rs/near-sdk/4.0.0/near_sdk/test_utils/fn.get_created_receipts.html once that `Promise` is dropped.

If you need accurate testing for this, your best bet is to use workspaces
