### ISSUE TITLE
Support "#[self_call]" for calls 

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-sdk-rs#122]
It should check whether the current account equals to the predecessor account.
```
    assert_eq!(env::current_account_id(), env::predecessor_account_id());
``` 

Most of the time when you implement a callback function, you have to lock it for calls from the contract itself. This method assert check is very common and probably should be supported by the SDK

**Comment by evgenykuzyakov** [comment]
Alternative name can be `#[private]`

**Comment by fckt** [comment]
Makes a lot of sense! I'm for `#[private]`
