### ISSUE TITLE
Figure out wasm type errors popping up on a mac.

### ISSUE THREAD

**Issue by ruseinov** [near/near-sdk-rs#1241]
This has only been confirmed on a Mac with an Apple chip so far.

After the `near-workspaces = "0.12"` update [store performance tests](https://github.com/near/near-sdk-rs/blob/dffe4b900d854bfa364db678250b635cff2ca0c2/near-sdk/tests/store_performance_tests.rs) started throwing errors.

```
"Link Error: \"function types incompatible: expected func of type `(i64) -> ()`, found func of type `(i32) -> ()`\"")) })) }
```

The problem does not present itself on `near-workspaces = "0.11"`. This deserves thorough investigation.

I've seen people [facing similar errors](https://github.com/bytecodealliance/wasmtime/issues/3594) on the net. Unsure if this is related, gotta dig into the changesets to figure that out.

**Comment by KevinMB0220** [comment]
I’m Kevin from Dojo Coding, and I would like to propose a solution for the issue related to the type compatibility error in `near-workspaces = "0.12"`. My approach involves investigating the differences in function implementations between versions `0.11` and `0.12`, focusing on function signatures and changes in type handling. I would also test explicit type conversions to ensure compatibility. I am committed to conducting a thorough analysis and proposing fixes to maintain stability across all platforms, including Macs with Apple chips.

**Comment by Sravya-212** [comment]
@ruseinov  I want to work on this

**Comment by dj8yfo** [comment]
this has been fixed by fix of https://github.com/near/nearcore/issues/12062 after it landed into `near-workspaces`
