### ISSUE TITLE
remove direct dependency on `cargo-near-build` in some of examples

### ISSUE THREAD

**Issue by dj8yfo** [near/near-sdk-rs#1257]
this is 6-liner TODO, which depends on https://github.com/near/near-workspaces-rs/pull/386 to remove direct import and use reexported version. 

- [x] examples/non-fungible-token/Cargo.toml
  - https://github.com/dj8yfo/near-sdk-rs/blob/b4b3dff0ef5a3f30841348a80461efc56f97945f/examples/non-fungible-token/Cargo.toml#L14
- [x] examples/lockable-fungible-token/Cargo.toml
  - https://github.com/dj8yfo/near-sdk-rs/blob/b4b3dff0ef5a3f30841348a80461efc56f97945f/examples/lockable-fungible-token/Cargo.toml#L18
- [x] examples/fungible-token/Cargo.toml
  - https://github.com/dj8yfo/near-sdk-rs/blob/b4b3dff0ef5a3f30841348a80461efc56f97945f/examples/fungible-token/Cargo.toml#L12

**Comment by virajbhartiya** [comment]
Can I work on this?

**Comment by dj8yfo** [comment]
@virajbhartiya sure
