### ISSUE TITLE
CI is not running on master commits

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#156]
If we look at the commits in the master branch we can see that CI does not run on them. @ailisp Could you please take a look at it? Maybe we broke it during nearprotocol -> near migration?

**Comment by ailisp** [comment]
Looks it's not due to #157 but possibly this:
![image](https://user-images.githubusercontent.com/13259400/82379834-70a5f280-99dc-11ea-94c1-99793e3a27a6.png)
I just turned on "build on push" (this includes a branch is merged to master). let's see if it works on next prs

**Comment by ailisp** [comment]
Looks it's running on master now
