### ISSUE TITLE
Some Map and Set collection methods fail tests

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#159]
I've created a pull request to illustrate this behavior. Please visit https://github.com/near-examples/nfts/pull/14. I'm copy/pasting the details mentioned in the description now:

The purpose of this PR is to share with the NEAR Collective in illustrating an issue that seems to be occurring with the collections [Set](https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/collections/set.rs) and [Map](https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/collections/map.rs) when applied to testing in the mocked blockchain context.

[Note line 107](https://github.com/near-examples/nfts/pull/14/files#diff-3c4c6049ddabf4205eeef1ccd59ff6c5R107) of `contracts/rust/src/lib.rs` calling a function `workaround()`. This workaround essentially inserts useless values into a Map and Set. After doing this, the tests work as expected. If the call to `workaround()` is commented out, we receive:

>thread 'tests::add_revoke_access_and_check' panicked at 'called `Result::unwrap()` on an `Err` value: InconsistentStateError(IntegerOverflow)', /Users/mike/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-0.9.2/src/environment/mocked_blockchain.rs:397:9

You'll note that there are two mocked context happening here. This is modeled after the tests found here:
https://github.com/near/near-sdk-rs/blob/master/examples/fungible-token/src/lib.rs#L295-L311

This seems of high importance for folks building Rust contracts and trying to write tests for the two data structures mentioned. For what it's worth, I believe this was specifically happening on the Set's `.remove` and I also saw this behavior on `.clear`.

**Comment by nearmax** [comment]
This has lower priority than the work on the core contracts. Assigning it @evgenykuzyakov since he recently fixed a bug in the collection.

**Comment by chadoh** [comment]
@amgando and I were seeing the same exact error as of commit https://github.com/near-examples/nfts/pull/9/commits/80b1ff17d333d80f28a3a87ce9f807b44e2b7bee in our AssemblyScript contract tests, and the same workaround (https://github.com/near-examples/nfts/pull/9/commits/2f5b6677be4635d623fd1451648b8ecb9c95b22e) fixed the issue there as well – not sure if this helps track down the bug.

**Comment by mikedotexe** [comment]
Okay, I believe the `storage_usage` is not updating properly for testing. For some reason, the workaround linked there will actually increase it, but it won't otherwise.
For Rust tests we can bump it up with the `VMContext` by setting a larger value like here:
`storage_usage: 300,`
I'm not sure what the solution is for AssemblyScript tests.
By the way, I tried this on testnet and the storage is working as expected. (I added some values to a Map, checked the `storage_usage` via a helper function, added some more and saw it increase.)
So this does seem to be a problem in testing only. 
Since testing is the way developers iterate, a fix would be really good though.

**Comment by mikedotexe** [comment]
Closing, basically I think if we're going to be switching contexts for testing, we either need to give it a ton of `storage_usage` or make sure we "reuse" it. This likely applies to other items like `attached_deposit`, `prepaid_gas`, etc.
