### ISSUE TITLE
Add constants to sdk like NEAR

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#160]
SDK should contain basic set of constants, for example:

*   `YOCTO_NEAR = 1`
*   `MILLI_NEAR = ...`
*   etc
*   `NEAR = 1^24 * YOCTO_NEAR`

**Comment by frol** [comment]
I believe, strongly-typed balance type is a better option, so you cannot suddenly add a value in NEAR to a value in yoctoNEAR.

```rust
struct Balance {
    yocto_balance: u128,
}
```

, and implement `Add`, `Sub`, `Mul`, etc operations ([derive_more](https://jeltef.github.io/derive_more/derive_more/) can help with code generation for those)

**Comment by frol** [comment]
In addition to what I wrote in my previous comment, I also want to propose we have FromStr implementation that can handle not only the raw u128 yoctoNEAR value, but also "1N" and "1yN" (or "1y", I have no strong opinion here).

/cc @evgenykuzyakov

**Comment by austinabell** [comment]
Done a while ago with https://github.com/near/near-sdk-rs/pull/640.

This is opinionated what other abstractions there can be, which can be done outside the SDK, but that change should be all that's needed. Open up again if anyone disagrees
