### ISSUE TITLE
Debug implementation for near sdk collections

### ISSUE THREAD

**Issue by amiyatulu** [near/near-sdk-rs#180]
Getting a hard time for pretty-printing the near protocol collections, how to implement the Debug for Map, Set, and Vector.

```
 use std::fmt;    
 impl fmt::Debug for Map<??> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result { 
                                                                ??
                                                   }
  }
```

**Comment by evgenykuzyakov** [comment]
What output would you like to see?
- All elements?
- Prefix?
- Some elements and length?

**Comment by amiyatulu** [comment]
All of these can help in debugging.

**Comment by austinabell** [comment]
Closing in favour of #564 (duplicate)
