### ISSUE TITLE
[Discussion] Be explicit that `near_sdk::collections::*` is an alias of the database?

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#183]
Our users are getting confused by a similar problem over and over again – they think that our `near_sdk::collections::**` is just like `sts::collections::**`, i.e. it operates and has a lifetime just like any other in-memory object. In reality, `near_sdk::collections::*` is an alias over the state trie, i.e. it acts like an ORM. We, however, put a lot of effort trying to hide it away, thinking that this will improve DevX. Unfortunately, it seems like users needs to be deeply aware of the fact that this is not an ordinary in-memory collections, but is just an alias over the database. Issues like this one: [https://github.com/near/near-sdk-rs/issues/182](https://github.com/near/near-sdk-rs/issues/182) demonstrate the confusion.

The big discussion question: should we make it more explicit that `near_sdk::collections::**` is an ORM, e.g. by renaming it to `near_sdk::kvstore::**`? (we should not use the word ORM since it has lots of misinterpretations, and even though it is frequently used outside relational databases, it still have a word "relational" in it)

What else should we do to make it more explicit? CC @willemneal , @mikedotexe , @chadoh @amgando , @evgenykuzyakov , @fckt

**Comment by chadoh** [comment]
Renaming seems like a great first step. Can we use `near_sdk::storage::*`?

**Comment by amgando** [comment]
> _Renaming seems like a great first step._

in general I think we would benefit from an editorial review of names across `near-sdk-rs` and `near-sdk-as` to minimize (or eliminate differences).  if there's no difference between these interfaces then it's less likely to cause confusion while studying examples across different contract technologies, the explanation can happen once (and iterated on in one location) and staying in sync over the long term will be easier (to automatically detect, or at least notice, gaps between the SDKs).  bonus: any new implementation will have a clear line to follow among 2 technologies.

for this reason i suggest we stick with the Rust `snake_case` naming convention for all methods and make sure we have parity.  `storage` is a better name, for example.

**Comment by ilblackdragon** [comment]
How about both renaming away from collections to storage and restricting their usage inside structures?
E.g. by not implementing BorshSerialize/Deserialize they won't be able to allocated inside a structure anymore.

Instead making them global (similar how it is in AS for us and Solidity with "mapping"), something like this:
```
const ACCOUNT_TABLE = near_storage_table!("a", AccountId, Account);
```

Con with this is that it makes a bit harder to track which "tables" exist in the contract, especially if other included cargos are registering their own.

Ideally this would include some kind of information at debug / testing mode to show all the tables.
Also it should fail if there are two tables with the same name used.

Separately, but related - we should figure out how this kind of things will be upgraded.
One option is that you can add new structure with new prefix and have a migration script that would migrate old one into new one. This requires though iteration over all elements - but we removed iterators.

Another option is some sort of enum with versioning is another option how we do it in nearcore, where it would deserialize old version of `Account` and save always new version: `enum Account { AccountV1(..), AccountV2(..) }`

**Comment by austinabell** [comment]
the new versions of collections are now being put in `near_sdk::store` and are currently unstable.

Not quite sure if there is anything more to be discussed on this, so will leave open for now. Is there still discussion to be had around how we can disallow developers from having overlapping prefix usage or showing the structure of the data somehow?

**Comment by austinabell** [comment]
These details are documented in https://docs.rs/near-sdk/4.1.0-pre.3/near_sdk/store/index.html and https://docs.near.org/sdk/rust/contract-structure/collections#error-prone-patterns
