### ISSUE TITLE
Update doc in fungible contract

### ISSUE THREAD

**Issue by fckt** [near/near-sdk-rs#192]
[https://github.com/near/near-sdk-rs/blob/375be66806aab2d0182049be1288753867bd304d/examples/fungible-token/src/lib.rs#L8-L12](https://github.com/near/near-sdk-rs/blob/375be66806aab2d0182049be1288753867bd304d/examples/fungible-token/src/lib.rs#L8-L12)

is not relevant for now, must be removed or updated

**Comment by austinabell** [comment]
This comment doesn't exist anymore, closing
