### ISSUE TITLE
Generate snake and came case for each contract method

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#209]
See discussion and proposed solution here: https://github.com/nearprotocol/NEPs/issues/96#issuecomment-660516538 Assigning to @evgenykuzyakov and cc-ing @olonho to keep him in the loop.

**Comment by austinabell** [comment]
Following the discussion on the linked issue, it seems like this is not an ideal path to have the duplication because it incurs hidden costs and functionality to everyone, even if they don't use it. Feel free to re-open if you think otherwise, but the issue seems stale to me
