### ISSUE TITLE
Error on context update

### ISSUE THREAD

**Issue by amiyatulu** [near/near-sdk-rs#216]
Updating the state by changing the context gives error:

```
 #<span class="error">[test]</span>
 fn set_then_get_greeting() 

 { let mut context = get_context(vec![], false); testing_env!(context.clone()); let mut contract = Welcome::new(); contract.set_record("7dd".to_owned()); context.block_timestamp += 1000; testing_env!(context.clone()); contract.update_record("7dd".to_owned()); } 

```

Error:
 thread 'tests::contract_test' panicked at 'called `Result::unwrap()` on an `Err` value: InconsistentStateError(IntegerOverflow)', /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/near-sdk-1.0.0/src/environment/mocked_blockchain.rs:389:9

Code:
 [https://gateway.ipfs.io/ipfs/QmTNHuRryBoDmTp7wqmNsCcJW8Gu7G6dz3cE3F4pynv6V9](https://gateway.ipfs.io/ipfs/QmTNHuRryBoDmTp7wqmNsCcJW8Gu7G6dz3cE3F4pynv6V9)

**Comment by amiyatulu** [comment]
The issue seems to be not fixed in near-sdk-rs 2.0.0, any work around to solve it?

**Comment by bowenwang1996** [comment]
Can you try setting `storage_usage` to a large number?

**Comment by amiyatulu** [comment]
Thank you. 😃 It worked like a charm.

**Comment by taylorjdawson** [comment]
@bowenwang1996 why does that fix it?

**Comment by bowenwang1996** [comment]
It can potentially cause integer underflow here https://github.com/near/nearcore/blob/65fcd0c8441694f6219a2ab33a81de7285315a66/runtime/near-vm-logic/src/logic.rs#L2031

**Comment by austinabell** [comment]
Can I close this? not sure if this is still triggerable, but I can't replicate
