### ISSUE TITLE
1.0.0 version breakage post mortem

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#219]
It is unclear how we broke 1.0.0 version. We need to write a postmortem of this incident so that we know how to prevent it in the future.

See incident here: https://github.com/near/near-sdk-rs/issues/218 and here: https://nearprotocol.pagerduty.com/incidents/P77KI08

**Comment by nearmax** [comment]
Setting to P0 since @chefsale asked to present it tomorrow.

**Comment by chefsale** [comment]
Thanks for filling the issue, in pagerduty postmortems (under analytics i believe) you can fill it out.

**Comment by evgenykuzyakov** [comment]
Wrote a postmortem here: https://nearprotocol.pagerduty.com/postmortems/162e531f-8aba-f101-90ff-3680ae46baa6

**Comment by evgenykuzyakov** [comment]
Added @olonho for review

**Comment by olonho** [comment]
Reviewed postmortem. Mostly agreed, although believe that profiling change per se is just a trigger, and the real issue is pretty complex publishing protocol of making changes and publishing SDK.
