### ISSUE TITLE
Unable to initialise vector in near_sdk 2.0.0

### ISSUE THREAD

**Issue by amiyatulu** [near/near-sdk-rs#237]
```
pub fn testVector() {
        let prefix = b"v".to_vec();
        let mut vec = Vector::new(prefix.clone());
    }
```

Gives error:
let mut vec = Vector::new(prefix.clone());
    |             -------   ^^^^^^^^^^^ cannot infer type for type parameter `T`
    |             |
    |             consider giving `vec` the explicit type `near_sdk::collections::Vector<T>`, where the type parameter `T` is specified

**Comment by evgenykuzyakov** [comment]
Vector needs a value type, and it looks like it can't be inferred from your code.

So you can address this either using by given the type explicitly on left side:
```rust
let mut vec: Vector<String> = Vector::new(prefix.clone());
```

Or give it on the right side:
```rust
let mut vec = Vector::<String>::new(prefix.clone());
```
