### ISSUE TITLE
Fix: dependency issue with near-sdk-sim being added to a project

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#243]
Currently if `near-sdk-sim` is added as a dependency to a contract project it fails to build because it tries to compile the simulation's dependencies even though `#[cfg(not(target = "wasm32"))]` is added to types generated by the new macro.

However, `near-sdk-sim` is not required in building the contract so it can be placed under `[dev-dependencies]`.  This fixes the build issue but then fails to build the integration tests because when compiling the contract it can't find `near-sdk-sim`.

Furthermore, `nightly` is required to run the tests.  

@frol do you have time next week to help me with this issue?

**Comment by frol** [comment]
@willemneal will [platform-specific dependencies](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#platform-specific-dependencies) help?
