### ISSUE TITLE
_serde::Serialize` is not implemented for `near_sdk::collections::Vector<u64>`

### ISSUE THREAD

**Issue by amiyatulu** [near/near-sdk-rs#248]
Tests are not giving any error but it produces error while building wasm release.

https://github.com/amiyatulu/serde-error

--> src/avrit/schelling_game.rs:22:1
   |
22 | #[near_bindgen]
   | ^^^^^^^^^^^^^^^ use of undeclared type or module `near_blockchain`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `near_sdk::collections::Vector<u64>: avrit::avritstructs::_::_serde::Serialize` is not satisfied
    --> src/avrit.rs:102:1
     |
102  | #[near_bindgen]
     | ^^^^^^^^^^^^^^^ the trait `avrit::avritstructs::_::_serde::Serialize` is not implemented for `near_sdk::collections::Vector<u64>`
     | 
    ::: /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.59/src/ser.rs:2189:17
     |
2189 |     T: ?Sized + Serialize,
     |                 --------- required by this bound in `near_sdk::serde_json::to_vec`
     |
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `avrit::Avrit: avrit::avritstructs::_::_serde::Serialize` is not satisfied
    --> src/avrit.rs:352:1
     |
352  | #[near_bindgen]
     | ^^^^^^^^^^^^^^^ the trait `avrit::avritstructs::_::_serde::Serialize` is not implemented for `avrit::Avrit`
     | 
    ::: /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.59/src/ser.rs:2189:17
     |
2189 |     T: ?Sized + Serialize,
     |                 --------- required by this bound in `near_sdk::serde_json::to_vec`
     |
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0277]: the trait bound `near_sdk::collections::LookupSet<u128>: avrit::avritstructs::_::_serde::Serialize` is not satisfied
    --> src/avrit/schelling_game.rs:22:1
     |
22   | #[near_bindgen]
     | ^^^^^^^^^^^^^^^ the trait `avrit::avritstructs::_::_serde::Serialize` is not implemented for `near_sdk::collections::LookupSet<u128>`
     | 
    ::: /home/amiya/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.59/src/ser.rs:2189:17
     |
2189 |     T: ?Sized + Serialize,
     |                 --------- required by this bound in `near_sdk::serde_json::to_vec`
     |
     = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by amiyatulu** [comment]
Ya, got it. Fix the issue The error was because of using pub function that returns LookupSet<u128> or Vector<u64>

**Comment by mikedotexe** [comment]
Glad you figured it out @amiyatulu ! Thanks for your involvement in the issue queue, too. 🙏🏼
