### ISSUE TITLE
Cannot add #[near_bindgen] for impl in separate file

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#257]
This has been reported by Thor from the community/partner scene.

>Btw, I've noticed that when I want to modularize by code a bit by breaking impl blocks across a couple files
 >I can't declare #<span class="error">[near_bindgen]</span> in several files, though I can declare it on multiple impl blocks within the same file, so it ends up that the whole contract must live in one file
 >this mildly annoying but not breaking problem, just curious if you were aware of it
 >The gods of mild annoyance, at the foot of whom we practice our craft, are pleased at this offering

**Comment by thor314** [comment]
documentation of issue:
https://github.com/thor314/near_multibindgen_bug

**Comment by bowenwang1996** [comment]
Lockup implementation has `#[near_bindgen] ` in multiple files https://github.com/near/core-contracts/tree/master/lockup/src

**Comment by oysterpack** [comment]
> documentation of issue:
> https://github.com/thor314/near_multibindgen_bug

I can confirm that this is definitely an issue because I had to use the `use crate::*` hack to work around this on the [STAKE][1] project.

[1]: https://github.com/oysterpack/oysterpack-near-stake-token

**Comment by austinabell** [comment]
Ah, this is an issue specifically around the types generated for sim tests. The `<Struct-name>Contract` type is only compiled for non-wasm targets for convenience.

https://github.com/austinabell/near_multibindgen_bug/commit/15c7455c0c65d508935d6e553c71526650432e1b is the workaround, but I can try to think of a backwards-compatible way to fix this in a general case

**Comment by austinabell** [comment]
Shouldn't have to deal with this as of 4.0 of the SDK. Re-open if you do
