### ISSUE TITLE
Fungible token example not compiling

### ISSUE THREAD

**Issue by thor314** [near/near-sdk-rs#259]
The fungible token simulation test example isn't compiling. https://github.com/near/near-sdk-rs/tree/master/examples/fungible-token

I've documented my attempts at getting it to compile in isolation from the `near-sdk-rs` repo here: https://github.com/thor314/FungibleToken

**Comment by austinabell** [comment]
There is https://github.com/near-examples/FT which is a current example of how to have this setup at the current version
