### ISSUE TITLE
hashmap load state

### ISSUE THREAD

**Issue by yp945** [near/near-sdk-rs#261]
When I use hashmap, I insert a large amount of data at once. Will it take a lot of time for the contract to load these states next time?

**Comment by yp945** [comment]
I see that writing and reading are based on contracts

![image](https://user-images.githubusercontent.com/15030378/102846270-7ff58e80-444a-11eb-86bf-26b84444a94d.png)

**Comment by bowenwang1996** [comment]
If you are talking about `std::collections::HashMap` then yes. If you want to store a lot of data it is better to use `near_sdk_rs::collections::Map`

**Comment by yp945** [comment]
thx,  when using LookupMap, it will directly insert data into the blockchain, so it is fast, but it is also included in the contract structure. When the contract structure is serialized, Will the data in the LookupMap be serialized twice

**Comment by bowenwang1996** [comment]
No. If you look at what the struct really is, it doesn't contain data https://github.com/near/near-sdk-rs/blob/08bd75562d55c5cd6a692456b6745b6f594c18b6/near-sdk/src/collections/lookup_map.rs#L17

**Comment by yp945** [comment]
I understand, thank you very much
