### ISSUE TITLE
#[near_bindgen] macro is not able to detect that func is public when implemented for a trait on the contract for simulation testing

### ISSUE THREAD

**Issue by oysterpack** [near/near-sdk-rs#262]
I found this "issue" while trying to integrate simulation tests ... my contract implements traits, which means that the funcs are implied to be public, however the #<span class="error">[near_bindgen]</span> macro is not able to detect that the func are public, e.g.,

```rust
 pub trait ContractOwner 

 { fn owner_id(&self) -> AccountId; } 

#<span class="error">[near_bindgen]</span>
 impl ContractOwner for StakeTokenContract {
 fn owner_id(&self) -> AccountId 

 { self.owner_id.clone() }

 ...

 }

 ```

 ```rust

 // sim test code 

 let res = view!(contract.owner_id());

 ```

 > let res = view!(contract.owner_id());

 > | ^^^^^^^^^^^^^ method not found in `StakeTokenContractContract`

 I can get it to work if the contract does not implement the trait:

 ```rust

 #<span class="error">[near_bindgen]</span>

 StakeTokenContract {

 pub fn owner_id(&self) -> AccountId { self.owner_id.clone() } 

...
 }
 ```
 The `near_bindgen` does not appear to be aware that the contract is implementing a trait.

I am using:
 ```toml
 <span class="error">[dependencies]</span>
 near-sdk = 

 { git = "https://github.com/near/near-sdk-rs", tag = "2.3.0" } 

<span class="error">[dev-dependencies]</span>
 near-sdk-sim = 

 { git = "https://github.com/near/near-sdk-rs", tag = "2.3.0" } 

```

**Comment by willemneal** [comment]
I'm a little confused with your example.  The method in question is `owner_id`, but then in your view call you call `owner_balance`.  Is this a typo?

**Comment by oysterpack** [comment]
> I'm a little confused with your example. The method in question is `owner_id`, but then in your view call you call `owner_balance`. Is this a typo?

correct - I fixed the example

**Comment by willemneal** [comment]
Hmm, well if you `cargo install wasm-nm` and then do `wasm-nm -e path/to/file.wasm` do you see `owner_id` listed?

Do you have branch where I can see this in action?

**Comment by oysterpack** [comment]
The problem is not in the wasm file. When I deploy the contract, it works just fine. The problem is with code generated by wasm_bindgen does not pick up the method visibility:

https://github.com/oysterpack/oysterpack-near-stake-token/blob/main/contract/tests/account_management.rs

```rust
#[test]
fn near_sdk_issue_262_near_bindgen_does_not_detect_pub_visibility_from_trait() {
    let ctx = test_utils::create_context();
    let contract = ctx.contract;

    // works because public method is defined directly on the contract
    let res = view!(contract.get_staking_pool_id());
    assert!(res.is_ok());

    // `staking_pool_id` is defined on the `StakingService` trait which the contract implements
    // but the method is not publicly visible on `StakeTokenContractContract`
    // let res = view!(contract.staking_pool_id());  // will not compile

    // but it is there if onvoked with the "low level" approach:
    let res = ctx.contract_operator.view(PendingContractTx::new(
        &contract.user_account.account_id,
        "staking_pool_id",
        json!({}),
        true,
    ));

    assert!(res.is_ok());
    let staking_pool_id: String = res.unwrap_json();
    assert_eq!(staking_pool_id, "astro-stakers.poolv1.near");
}
```

**Comment by oysterpack** [comment]
I moved the sample code to a separate file: https://github.com/oysterpack/oysterpack-near-stake-token/blob/main/contract/tests/near_sdk_rs_issue_262.rs

**Comment by austinabell** [comment]
sim tests deprecated and no longer need to use those types for workspaces
