### ISSUE TITLE
bug: near-sdk 2.0.0

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-sdk-rs#265]
seems the issue with `syn` crate that was somehow triggered by the `borsh` version bump.

For now let's issue `near-sdk 2.0.1` without any changes, because it created a bunch of side effects from nearcore dependency. Let's create a new branch with only `syn` version to be fixed to `"=1.0.57"`

**Comment by artob** [comment]
Previously in nearcore: https://github.com/near/nearcore/pull/3785

**Comment by evgenykuzyakov** [comment]
Published `2.0.1` crate and released a tag
