### ISSUE TITLE
Collections' new method's parameter should be called prefix, not id

### ISSUE THREAD

**Issue by abacabadabacaba** [near/near-sdk-rs#268]
Currently, the `new` method for some collection types has its parameter named `id`. This can make the user falsely assume that it is enough that different collections have different `id` values.

Actually, this value is used as a prefix. If the user chooses two different `id` values such that one of them is a prefix of the other, it is possible that collections having these `id` values would use the same storage key, leading to incorrect behavior.

To fix this, all of these `id` parameters should be renamed to `prefix`. Also, we should have better documentation about using collections safely (some overview document in addition to rustdoc). Ideally, we should have the exact storage representation documented as well.

**Comment by austinabell** [comment]
This isn't the case in current SDK. id seems to be only used internally for the old TreeMap impls
