### ISSUE TITLE
Simulation doesn't pick up trait methods

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#276]
When contract is extended by some trait, simulation doesn't pickup methods from such trait.

Here is the specific example: https://github.com/near/near-sdk-rs/pull/275/files#diff-c9d9a69215d48e7b6c0345518f9c69ccb5e5afa7fde895d04aabd72b139c667fR43

# Steps to reproduce

Check out ` add-near-std` branch and try to run `general.rs` test in examples/fungible-token

Observe:
```
error[E0599]: no method named `transfer` found for struct `fungible_token::FungibleTokenContract` in the current scope
  --> tests/general.rs:67:18
   |
67 |         contract.transfer(alice.account_id.clone(), transfer_amount.into()),
   |                  ^^^^^^^^ method not found in `fungible_token::FungibleTokenContract`

```

**Comment by ilblackdragon** [comment]
Any updates on this? It's blocking merge of the #275 PR.

**Comment by willemneal** [comment]
Yeah Here: https://github.com/near/near-sdk-rs/pull/284
