### ISSUE TITLE
feat: make the default json serializer-deser automatically convert u64 & u128 to/from string

### ISSUE THREAD

**Issue by luciotato** [near/near-sdk-rs#286]
It will be very useful if the json serializer-deserializer used by the contracts, would automatically ser-deser u64 & u128 to/from String.  I find myself having to create 2 structs in the smart contracts,  one to store the data in State, and the other to get/pass information out. Both are the same except u64,u128 replaced by U64,U128 so the json-serializer does the right thing.

Serializing u64 & u128 to json number makes no sense because you'll be losing data in very obscure and hard to detect ways. 

If u64 & u128 are ser-deser to-from String, we can use the same structs for storage and communication.

bonus: we can just use u64 & u128 for pub fn args

related to #7

**Comment by evgenykuzyakov** [comment]
While I agree that it can be beneficial, but it will break legacy `u64` support. In the past I used `u64` in method returns when I knew the value will never exceed `2e53`.

**Comment by evgenykuzyakov** [comment]
We can introduce this for `u64/u128` with a compilation feature, if `serde` supports it

**Comment by austinabell** [comment]
Closing to just focus discussion in #408
