### ISSUE TITLE
Unclear where `contract:` argument comes from

### ISSUE THREAD

**Issue by joshuajbouw** [near/near-sdk-rs#298]
In the contract example using the `deploy!` macro it is unclear exactly what needs to be put into the `contract:` field. I had found that it apparently comes from a `fungible-token` crate however, it doesn't exist:

```toml
 [<span class="error">[package]</span>]
 name = "fungible-token"
 version = "0.3.0"
 dependencies = [
 "near-sdk",
 "near-sdk-sim",
 ]
 ```
 Search yields nothing in crates.io: [https://crates.io/search?q=fungible-token](https://crates.io/search?q=fungible-token)

**Comment by ilblackdragon** [comment]
Fungible token crate is in the examples/fungible-token in this repo.

`deploy!` macro comes from near-sdk-sim that gets generated for given contract.

@willemneal we need documentation for all this for simulation framework.

**Comment by austinabell** [comment]
sim tests deprecated in favour of workspaces
