### ISSUE TITLE
TreeMap implementation potentially has bugs

### ISSUE THREAD

**Issue by evgenykuzyakov** [near/near-sdk-rs#299]
The TreeMap panicked at `tree_map.rs:567:62` for commit https://github.com/near/near-sdk-rs/commit/1d3535bd131b68f97a216e643ad1cba19e16dddf

Discovered on testnet: https://explorer.testnet.near.org/transactions/2JB3Hg4xyHmYv1HzF34zWVffhaEUg6TTherrGdBGrTxx

**Comment by evgenykuzyakov** [comment]
It looks like TreeMap got into inconsistent state after this transaction: https://explorer.testnet.near.org/transactions/5ipanH55qEgoYqZ8EVZVAaHaPXPYEinyAJHnnYsxXQxY

**Comment by evgenykuzyakov** [comment]
Source: https://github.com/evgenykuzyakov/berry-hot/tree/master/contract/src

**Comment by evgenykuzyakov** [comment]
List of actions that triggered it. Can be used as a repro: https://gist.github.com/evgenykuzyakov/bd3392a16f135f7275737ee7b2599aa1

**Comment by evgenykuzyakov** [comment]
Final state of the parallel map (that's how TreeMap should look):
```
[
  [ 24518600, { wins: 1, views: 1 }, [length]: 2 ],
  [ 22704334, { wins: 1, views: 1 }, [length]: 2 ],
  [ 28465247, { wins: 1, views: 1 }, [length]: 2 ],
  [ 29660010, { wins: 1, views: 1 }, [length]: 2 ],
  [ 23675009, { wins: 1, views: 1 }, [length]: 2 ],
  [ 30232905, { wins: 1, views: 1 }, [length]: 2 ],
  [ 23915501, { wins: 1, views: 1 }, [length]: 2 ],
  [ 29685074, { wins: 1, views: 1 }, [length]: 2 ],
  [ 23928192, { wins: 1, views: 1 }, [length]: 2 ],
  [ 27165407, { wins: 1, views: 1 }, [length]: 2 ],
  [ 35515346, { wins: 1, views: 2 }, [length]: 2 ],
  [length]: 11
]
```

**Comment by robert-zaremba** [comment]
Is this going to be fixed any time soon? @nearmax  - I think it's important to handle it quickly and communicate with all builders with a proposed upgrade path.

**Comment by evgenykuzyakov** [comment]
It's not a bug. Seems I've used conflicting `PartialEq` and `Ord`.
