### ISSUE TITLE
Document using simulation framework without near_bindgen

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#301]
If developer not using `near_bindgen` for some functions because of using direct exports - simulation framework won't have these functions to be called.

We should have documentation to how to use simulation directly.

**Comment by willemneal** [comment]
Discussed this with @chadoh, and I think we need to rework the API so that `user.call`/`user.view` don't use `PendingContractTx` and instead just take `method`, `args`, etc.

**Comment by austinabell** [comment]
sim tests deprecated
