### ISSUE TITLE
Unsafe AccountId to ValidAccountId conversion

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#312]
Can we add unsafe AccountId to ValidAccountId conversion so it's easier to pass them between each other in tests?
It can be pragma tests, for example.

**Comment by evgenykuzyakov** [comment]
I think `#cfg(test)` doesn't propagate into other test modules. So the only option is to add into the `test_utils`

Should be fixed with strict types later

**Comment by austinabell** [comment]
No need for this since `AccountId` is now validated by default, with `new_unchecked` as an option for initializing without checking in release

**Comment by ilblackdragon** [comment]
I thought we created ValidAccountId to not check all the time validity when AccountId is just passed around?

**Comment by austinabell** [comment]
The change was initially proposed in https://github.com/near/near-sdk-rs/issues/387. (PR for reference https://github.com/near/near-sdk-rs/pull/448)

Having the two types was confusing for developers and led to a clunky API. Yes, there can be some slight overhead, but I think that the benefits outweigh this. It seems reasonable to have it validated by default, and if anyone wants to hyper optimize their contract, they can use `String` as the type and create their alias if they wish to and/or use `AccountId::new_unchecked`.

cc @mikedotexe @ChaoticTempest
