### ISSUE TITLE
near-sdk-sim doesn't support serializer(borsh)

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#321]
Currently then calling via call!(root, contract.method(arg)) -- to method that has `serializer(borsh)` on it, the passed value is still json.

**Comment by djsatok** [comment]
Blocking [NEP-141 support](https://github.com/near/rainbow-token-connector/pull/39) in the bridge.

**Comment by mfornet** [comment]
No longer P0, we were unblocked by a temporary fix https://github.com/near/near-sdk-rs/pull/325 by @willemneal

**Comment by ilblackdragon** [comment]
You can work around:
```
    root.call(
        PendingContractTx {
            receiver_id: dao.user_account.account_id.clone(),
            method: "stage_code".to_string(),
            args: DAO_WASM_BYTES.try_to_vec().unwrap(),
            is_view: false,
        },
        to_yocto("100"),
        near_sdk_sim::DEFAULT_GAS,
    )
    .assert_success();

```

**Comment by mfornet** [comment]
> You can work around:

Yes already doing something similar.

**Comment by mikedotexe** [comment]
@willemneal I think you may have resolved this over the last week?

**Comment by willemneal** [comment]
@mikedotexe See PR ;-)
