### ISSUE TITLE
Change license to GPL

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#333]
near-sdk-rs depends on nearcore which has GPL license, which means it should also be GPL.

**Comment by mikedotexe** [comment]
Hey @nearmax I know there have been a number of conversations about making crates more independent. I'll admit I haven't followed the discussions between @willemneal and @evgenykuzyakov but I do see the root `Cargo.toml` has commented out dependencies on `nearcore`.
https://github.com/near/near-sdk-rs/blame/master/Cargo.toml#L21-L22
This makes me want to ask Willem and Eugene if this issue still stands?

**Comment by willemneal** [comment]
@mikedotexe, the dependencies in nearcore were published and we depend on them in the sdk and the simulator.  Though the crates in nearcore are published with APACHE, so we should update those as well.

**Comment by evgenykuzyakov** [comment]
Created https://github.com/near/nearcore/issues/4140 to discuss GPL in nearcore, because I can't find a proper issue
