### ISSUE TITLE
Fungible token example doesn't transfer Ⓝ with storage_withdraw

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#342]
It appears that we didn't finish fleshing out the `storage_withdraw` function for the fungible token contract standard.
Particularly here:
https://github.com/near/near-sdk-rs/blob/661a14ead9c98c6a892937531d84418fe2af9baf/near-contract-standards/src/fungible_token/storage_impl.rs#L79

It looks like we're just returning the storage balance instead of using a Promise to send back the requested amount.

**Comment by chadoh** [comment]
This is by design and is correct, see https://github.com/near/near-sdk-rs/pull/309#discussion_r588001029

Maybe we could add a comment to the function explaining the logic, since multiple people have been confused by it
