### ISSUE TITLE
Incorrect version release

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#354]
We incorrectly released `3.0.1` instead of `3.1.0`, because new release contains API changes. Please see https://semver.org/ 

It is extremely important to follow conventions precisely, because package management tools rely on it to decide what version to use and when.

We cannot completely fix it now, since cargo does not allow to yank versions. However, we need to publish `3.1.0`.

**Comment by mikedotexe** [comment]
Hey Max, thanks for pointing this out. Version `3.1.0` has been published now.
https://crates.io/crates/near-sdk/3.1.0
