### ISSUE TITLE
Revisit HELP.md and workshop cross-contract call example

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#356]
The current PR for the `HELP.md` file is amazing and I'd love the community to have it ASAP. There was a section that was added toward the end that I've excised and I believe we can workshop on this idea a bit, adding clarity and whatnot. Here's what it was:

---

### Cross-contract call return values as inputs to callbacks

A common pattern is to call an external contract, then schedule a follow-up call to self in order to react to the outcome of the external call.
Continuing the example above, `Contract` could use the returned `U128` from `ext_calculator`.

Note that scheduling calls to the current contract can also use `ext_contract`.
It is common to use `ext_self` as the name when doing so.

E.g.

```rust
#[ext_contract(ext_self)]
trait OnCalculate {
    fn resolve_stats(&self, #[callback] sum: U128, caller: AccountId) -> Account;
}

#[near_bindgen]
impl Contract {
    pub fn calculate_stats(&mut self, a: U128, b: U128) -> Promise {
        let caller = env::predecessor_account_id();
        let calculator_account_id: AccountId = CALCULATOR_ACCOUNT_ID.to_string();
        ext_calculator::sum(a, b, &calculator_account_id, NO_DEPOSIT, BASE_GAS)
        .then(ext_self::finish_deposit(
            // note that we only pass `caller` here
            &caller,
            &env::current_account_id(),
            NO_DEPOSIT,
            BASE_GAS
        ))
    }

    pub fn resolve_stats(
        &mut self,
        #[callback]
        sum: U128,
        caller: AccountId
    ) -> Account {
        let account = self.accounts.get(caller)
            .unwrap_or_panic("account {} not found", caller);
        account.total += sum.0;
        account
    }
}
```

---

Let's group up and see how we'd like to address cross-contract calls and the various ways developers will use that.

**Comment by chadoh** [comment]
Can we make a PR for this, so we can view the change in the context of the larger document?

**Comment by mikedotexe** [comment]
> Can we make a PR for this, so we can view the change in the context of the larger document?

If this gets fleshed out, tested, and is clear, I think we can submit a PR. It doesn't feel like it's in that place yet so I moved it into an issue to preserve it in case we'd like to build on it or salvage ideas.

**Comment by itegulov** [comment]
Handled by @austinabell a while ago
