### ISSUE TITLE
[Epic: Rust Docs]

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#358]
This epic covers what Dev Platform is looking to achieve in Q2 of 2021, where a large part is leaning into the Rust documentation of this repository.

To see the Rust docs for this repo, navigate to the project root and run:

 cargo doc --open

Here are some links that demonstrate nice-looking Rust docs for inspiration:

1.  1.  1.  HashMap
             ***Docs***: [https://doc.rust-lang.org/std/collections/struct.HashMap.html](https://doc.rust-lang.org/std/collections/struct.HashMap.html)
             ***Code***: [https://github.com/rust-lang/rust/blob/master/library/std/src/collections/hash/map.rs](https://github.com/rust-lang/rust/blob/master/library/std/src/collections/hash/map.rs)

1.  1.  1.  Serde
             ***Docs***: [https://docs.serde.rs/serde/trait.Serialize.html#tymethod.serialize](https://docs.serde.rs/serde/trait.Serialize.html#tymethod.serialize)
             ***Code***: [https://github.com/serde-rs/serde/blob/e61261e002bca732a6bb89eab3b10911b43da668/serde/src/ser/mod.rs#L216-L250](https://github.com/serde-rs/serde/blob/e61261e002bca732a6bb89eab3b10911b43da668/serde/src/ser/mod.rs#L216-L250)

**Comment by matklad** [comment]
Relevant section of the Rust API guidelines: https://rust-lang.github.io/api-guidelines/documentation.html
