### ISSUE TITLE
Status Message Cargo.toml Path to NEAR-SDK-RS Error

### ISSUE THREAD

**Issue by kcelestinomaria** [near/near-sdk-rs#367]
In the Status message example, on the Cargo.toml file I am trying to refer back to the path referring to the NEAR-SDK-RS location, wouldn't it be easier if there was a default location say on someone's filesystem or on github that the Cargo.toml dependencies reference could refer to?
Like it refers to "../../..near-sdk-rs" which is a path to the near rust sdk specifically on the github repository
I want to change that and make it refer to the location of near-sdk-rs on sm's terminal filesystem by default
Cause anytime I try to run Cargo build in order to update the dependencies then it cannot call the path to the near-sdk-rs

**Comment by austinabell** [comment]
Can just switch the dependency to:
```toml
near-sdk = "4.0.0-pre.2"
```

Or whatever version you want to use.

We don't currently provide the guarantee that there are no breaking changes that affect the contract since the most recently released version, so there might need to be a few small changes in some cases
