### ISSUE TITLE
move near-sdk-core crate into near-sdk-macros

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#369]
`near-sdk-core` and `near-sdk-macros` are two crate which look like they should be one. The `-core` crate just defines the proc-macro machinery that is invoked from (and only from) the `-macros` crate.

Merging the two has the following benefits:

* one less semver version to manage / crate to publish
* one less entry in Cargo.lock for contract authors (fighting perception that Cargo is like npm)
* less confusion about what `near-sdk-core` is -- the name sounds like this crate defines the core runtime types of the SDK for the purposes of greater stability (like rand-core or rayon-core). But in fact its just the opposite -- it's the private impl details of a proc macro

While we are at it, it makes sense to fix nonsensical cfgs in this crate:

https://github.com/near/near-sdk-rs/blob/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk-core/src/code_generator/item_impl_info.rs#L17-L23

This is a proc macro, so `target_arch` is *never* wasm32

**Comment by willemneal** [comment]
> This is a proc macro, so target_arch is never wasm32

@matklad  Can you explain this? I thought that the proc macro was being used when targetting `wasm32`.

**Comment by austinabell** [comment]
> > This is a proc macro, so target_arch is never wasm32
> 
> @matklad Can you explain this? I thought that the proc macro was being used when targetting `wasm32`.

It is, I believe what he means is that there is some code generated with tags for each arch, which I've noticed when expanding the proc macro.

Basically the attribute should be applied to the code that generates in the proc macro, and the generated code should not include this

**Comment by willemneal** [comment]
I see, but in this example the it does generate different code based on the target.

**Comment by austinabell** [comment]
> I see, but in this example the it does generate different code based on the target.

Oh, yeah, perhaps what he's indicating is that these configs aren't respected in proc macros. I'll look into this now, and if so, my previous guess is wrong and can't be done.
