### ISSUE TITLE
For the simulator, automate away getting compiled code of the contract

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#370]
There's a bunch of accidental complexity involved when getting `.wasm` into the simulator:

 [https://github.com/near/near-sdk-rs/tree/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk-sim#test-files](https://github.com/near/near-sdk-rs/tree/31cba6213919ec4866bc0fab7f6963de241cc43a/near-sdk-sim#test-files)

>near_sdk_sim::lazy_static_include::lazy_static_include_bytes! 

 { > // update `contract.wasm` for your contract's name > CONTRACT_WASM_BYTES => "target/wasm32-unknown-unknown/release/contract.wasm", > > // if you run `cargo build` without `--release` flag: > CONTRACT_WASM_BYTES => "target/wasm32-unknown-unknown/debug/contract.wasm", >} 

>
 > Note that this means ***you must build before you test***!

I think we should be able to automate this away. 

I imagine API like

```rust
 pub fn read_rust_contract(path_to_crate: &Path, contract_name: &str) -> &'static <span class="error">[u8]</span> {
 }
 ```

Internally, this thing would:

*   lock a global static hash-map of already loaded contracts
*   if the contract is not yet loaded, run `cd path_to_crate && cargo build --release` and `std::fs::read(path_to_crate/target/release/contract_name.wasm)`

I can imagne an excended version for when you want to tweak things:

```rust
 let contract = load_contract_opt()
 .package("./fungible-token")
 .bin("fungible.token") // required only for crates with many contracts
 .release(true)
 .load();
 ```

**Comment by austinabell** [comment]
This problem is solved in workspaces by being able to get the wasm from compiling https://github.com/near/workspaces-rs/blob/7520d87d41d5f8ec6bcd6d8884dfd23b6623e1e5/README.md#updating-contract-afterwards
