### ISSUE TITLE
export data from rpc to simulate real block_height, gas_price etc.

### ISSUE THREAD

**Issue by ailisp** [near/near-sdk-rs#382]
We need collect realistic number from rpc to create a config for simulator, to reproduce testnet txn:
 ```
 pub struct GenesisConfig 

 { pub genesis_time: u64, pub gas_price: Balance, pub gas_limit: Gas, pub genesis_height: u64, pub epoch_length: u64, pub runtime_config: RuntimeConfig, pub state_records: Vec<StateRecord>, pub validators: Vec<AccountInfo>, } 

```

More specifially:

*   genesis_time, genesis_height shall be set to block_time, block_height just before txn happen
*   gas_price, gas_limit, epoch_length, runtime_config, validators should be set to realistic one of rpc said about the epoch / testnet genesis said
*   state_records is obtained by a script now, and load in #375
*   these data should be sufficient to reproduce most txn on testnet, if some txn need additional data to reproduce we would address as separate issues in the future

**Comment by bowenwang1996** [comment]
Is that sufficient? There are other things in `ApplyState` that you need as well to apply a transaction. Also `GenesisConfig` is not necessarily the best name here.

**Comment by ailisp** [comment]
@bowenwang1996 Not all ApplyState fields are valid to reproduce, for example `prev_block_hash` and `block_hash`, when you try to reproduce a transaction that had receipts to include in different blocks, block hash would be different than it is on testnet, due to testnet their are other txns included in blocks, while you reproduce you only replaying your transaction. Also simulator acts on higher level and unable to directly change the args passed into ApplyState, instead we can only influence the ApplyState by pass in a synthetic genesis, for example, change genesis_time to set block_time.

**Comment by bowenwang1996** [comment]
> Not all ApplyState fields are valid to reproduce, for example prev_block_hash and block_hash, when you try to reproduce a transaction that had receipts to include in different blocks, block hash would be different than it is on testnet

While that is true, I don't think it is an insurmountable obstacle. If the goal is to accurately reproduce the apply result of a transaction, you can fetch the blocks that include transaction and its receipts and match them manually. You will also need the state changes in between to accurately reproduce the result. However, if your goal is not to have a complete reproduction, then it is another story.

**Comment by matklad** [comment]
@bowenwang1996 just to clarify, [`GenesisConfig`](https://github.com/matklad/near-sdk-rs/blob/97fc632fcc58eb7ff7faad0be54ea8ec91dbf694/near-sdk-sim/src/runtime.rs#L42-L52) is what we already have implemented in the simulator. So I think it's best to follow a meet in the middle style approach here -- first use existing `near_sdk_sim::GenesisConfig` to get somewhat realistic reproduction, and then, once we have the pipeline working, refine its precision.

**Comment by ailisp** [comment]
> While that is true, I don't think it is an insurmountable obstacle. If the goal is to accurately reproduce the apply result of a transaction, you can fetch the blocks that include transaction and its receipts and match them manually. You will also need the state changes in between to accurately reproduce the result. However, if your goal is not to have a complete reproduction, then it is another story.

The cost seem to be too big, you'll also need to download all state of other contracts that has been accessed in the block. And for those transactions accounts and keys in used. If you only attempt re-run your transaction, you know what account was in used and thus you can provide them as arguments so near-sdk-sim can place this accounts and their keys in state_records. But for all transaction you had no knowedge, then near-sdk-sim has to figure out for you. I think in practice it's impossible because those not your transactions can cross contract call to any contract account (unless do a static analysis inside wasm files?). So the only practical way is to fetch and use entire state at the start block of transaction, but that is not scalable. Also I would argue the actual content of block hash would never be relied on a real contract because it's meaningless and unpredictable, it at most based on the logic of "whether this block hash exist on chain". Therefore only fetch state of the contract you're testing, although loss accuracy on block hash, should be better.

**Comment by ailisp** [comment]
@bowenwang1996 Please also take a look and comment on https://docs.google.com/document/d/10xKfwVhJIAYNVkgR0FPvzpsnI8-Gs9GgblygGGT1sxs where we're having further discussion on reproduce related designs. Thanks

**Comment by mikedotexe** [comment]
Note for those who may be looking for more information: please see this discussion:
https://gov.near.org/t/design-doc-of-near-sandbox/2264

**Comment by austinabell** [comment]
I believe https://github.com/near/workspaces-rs/issues/68 should cover this. Add more detail in that issue if it does not
