### ISSUE TITLE
Document API evolution strategy 

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#384]
Uplifting [https://github.com/near/near-sdk-rs/pull/366#issuecomment-823984897](https://github.com/near/near-sdk-rs/pull/366#issuecomment-823984897) to an issue:

>This is going to break legacy code. log! serves the purpose.

Do we have our backwards compatibility policy for SDK documented anywhere? Taking a bird's eye view, the current public API of SDK feels like it has a lot of rough edges from Rust API design point of view, and it seems like long term smoothing those out would be beneficial. However, it's unclear to me at least what is the best path towards that.

I can see several options for this particular change, and for this class of changes:

*   do nothing and consider the API frozen / append only
*   keep the current major version, but use deprecation to slowly clean-up the API (so, apply #<span class="error">[deprecated]</span> & #<span class="error">[doc(hidden)]</span> attributes to the log function, introduce `log_str`, re-implement `log` in terms of `log_str`)
*   use release trains: release a point release which deprecates `log` function now, and release a new semver-incompatible version not-to-far in the future, which adds log with the correct signature.
*   prepare for "big-bang" style next major version (don't implement this right now, but add a BreakingChange label and release a new version when we accumulate a bunch of those).
*   re-design the API from the first principles, using the lessons learned, but not the code, from the existing sdk (aka "don't tell Joel Spolsky")

Neither of them is inherently better than the other (even the last one can be beneficial in the exceptional circumstances), but it's unclear which one we use.

**Comment by matklad** [comment]
My current take:

We have three large classes of consumers of the sdk -- near core contracts, existing folks who already build on near, new folks who are just starting to use near.  Crucially, because of the second group, we just can't change the APIs left and right. 

I also feel that the API cleanup work is high-value -- it's not like we need to cleanup a couple of methods, we have entire types which do not make much sense for an abstract well-defined sdk (like gas being just a type alias rather than a newtype, or `ValidAccountId` existing).

So my proposal would be:

First and foremost, do internal API preserving cleanups first (#372, #373) as, at the moment, it's hard to say what our public API even is. It's unclear what exactly is exposed here, for example:

https://github.com/near/near-sdk-rs/blob/97fc632fcc58eb7ff7faad0be54ea8ec91dbf694/near-sdk/src/lib.rs#L26

Then, I think we should prioritize cleaning up the API in place -- add better APIs, mark old APIs as deprecated, release new semver compatible versions. That way, new users get nice APIs, and existing users can upgrade at their own leisure. To future-proof new API's, we might add them under `unstable` cargo feature first, and dogfood in the core contracts.

Some time in the future, we probably should cut *one* major release removing the deprecated cruft, and then commit to supporting that major version for quite some time.

**Comment by matklad** [comment]
I've just realised that I've conveniently squatted https://crates.io/crates/near, and, in terms of rust API, `near::log`, `near::storage_read` etc look sweat. So, if we decide to do a big cleanup some day, rebranding near-sdk as near and rewinding the major version back to 1 is an option!

**Comment by austinabell** [comment]
We should maybe be more explicit with our plan, but it has been shaping up as following this pattern:

> keep the current major version, but use deprecation to slowly clean-up the API (so, apply #[deprecated] & #[doc(hidden)] attributes to the log function, introduce log_str, re-implement log in terms of log_str)

For ease of transition from current contracts. There seem to be some fundamental changes that come with needing to minimize contract size and overall structure, but this might need to come with an API redesign, which might make sense to migrate over to the `near` crate if this happens.

**Comment by austinabell** [comment]
To summarize what happened, we burned a new major version `4.0` and didn't make any state-breaking changes. At all costs we will avoid silently breaking state (like in https://github.com/near/near-sdk-rs/pull/745 which throws an error for breaking pattern). All APIs will aim to maintain Rust's semver. Most APIs migrated slowly with deprecations, even through the major version.

Perhaps it would be valuable to convey this in the README or otherwise
