### ISSUE TITLE
near-sdk-sim calculates storage incorrectly 

### ISSUE THREAD

**Issue by skyward-dev** [near/near-sdk-rs#388]
For example, I'm trying to deploy wrap near contract with 10 NEAR. It works on the testnet, but doesn't work in the simulator tests.
```
let w_near = near.deploy_and_init(
            &W_NEAR_WASM_BYTES,
            WRAP_NEAR_ID.to_string(),
            "new",
            b"{}",
            to_yocto("10"),
            BASE_GAS,
        );
```
It looks like the simulator uses different storage per byte and fails with the following:
```
Outcome ExecutionOutcome {
    logs: [],
    receipt_ids: [
        `7qy1rGatQE1fCVd7V3neku5Hm9dvakY2LHiC8L3jERxh`,
        `5CBACqrLyeTEeVr3wB5dnyZ2LkYy2LAhospjfSMJjW9Z`,
    ],
    burnt_gas: 4673903491021,
    tokens_burnt: 467390349102100000000,
    status: Failure(Action #0: The account wrap.near wouldn't have enough balance to cover storage, required to have 6896582900000000000000000 yoctoNEAR more),
} was a failure
```

**Comment by evgenykuzyakov** [comment]
Hmm. It looks like it uses old protocol version for some reason. Let me investigate.
cc @willemneal Have you seen it before?

**Comment by willemneal** [comment]
@evgenykuzyakov Yeah I think we need to republish the nearcore crates.

**Comment by evgenykuzyakov** [comment]
I think the issue is the `RuntimeStandalone` doesn't upgrade the `RuntimeConfig`.
It's done in `RuntimeConfig::getConfig(config, protocol_version)` (or smth like that), which we don't call. We probably just need to call it at start and give default config.

**Comment by evgenykuzyakov** [comment]
Publishing [3.2.0] now. It should have correct storage cost per byte.
