### ISSUE TITLE
How to advance time in near-sdk-sim?

### ISSUE THREAD

**Issue by skyward-dev** [near/near-sdk-rs#389]
I need to move time by a day. Is it possible in the near-sdk-sim?

**Comment by evgenykuzyakov** [comment]
Publishied `near-sdk-sim` `3.2.0`. It exposes `cur_block` from `RuntimeStandalone`. You should be able to set `block_timestamp` to adjust time when the transaction starts. You may also want to set `block_prod_time` from `GenesisConfig` in the near-sdk-sim to `0`, so the `block_timestamp` doesn't change for the receipt.
