### ISSUE TITLE
Tracking issue for error standard in SDK

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#399]
Primarily in the `json_types` module, `Box<dyn std::error::Error>` is used as the error type, which can be hard to use sometimes and as @matklad pointed out [https://github.com/near/near-sdk-rs/pull/398#pullrequestreview-650502656](https://github.com/near/near-sdk-rs/pull/398#pullrequestreview-650502656) it is missing the `Send`/`Sync` bounds.

In my opinion, I think it would be the cleanest to use <span class="error">[thiserror]</span>([https://github.com/dtolnay/thiserror](https://github.com/dtolnay/thiserror)) for std::Error impls and potentially <span class="error">[anyhow]</span>([https://github.com/dtolnay/anyhow](https://github.com/dtolnay/anyhow)) on top of this to swap out the boxed std::error type and clean up error handling within the codebase.

Opinions would be much appreciated. These are not included in the sdk dependency tree yet, and I'm not yet sure exactly the footprint, but my intuition is the incremental addition is very small.

**Comment by matklad** [comment]
>which can be hard to use sometimes

To expand on this, the main issue with `Box<dyn error>` is that it can't be `?`-converted to `anyhow::Error` or similar dynamic errors (that is, the converse is true `anyhow` is not trivially `?`-compatible with other errors, like `Box<dyn Error>`). They are interoperable via explicit conversions, but that's 

In general, a good practice for libraries is to return a concrete type which implements std::error::Error. `json_types` should probably use `serde_json::Error`.

**Comment by austinabell** [comment]
I guess also the discussion can be around how specific these errors should be. Although module/type specific errors can be useful, they might not be easy to pick up and use as a newcomer to near-sdk/rust.

Also, even if using concrete types, the implementation of this can be simplified greatly by using `thiserror`
