### ISSUE TITLE
Comment on contract generation for simulation

### ISSUE THREAD

**Issue by zcstarr** [near/near-sdk-rs#423]
I ran into an issue, being new to the project and near contract development, where I was using the fungible token as a simulation test example. 

The issue I hit was not realizing the that near_bindgen creates a new struct with a differing contract name for the simulator. This is document in near-sdk-sim readme. 

I found this however easy to overlook and miss as I typically browse docs and look more closely at code. I thought a nice way to improve the documentation might be a little comment about ContractContract bit, with a pointer to more docs. 

so I filed a PR with a comment, but I'm open to suggestions or thoughts if this is a good/bad idea.

**Comment by austinabell** [comment]
I agree, this was quite confusing when I first looked and the only reason it became clear was a comment in an example.

Let's consider what the constraints are and if we can do better.

**Comment by austinabell** [comment]
Related #257

**Comment by austinabell** [comment]
sim test codegen was removed in 4.0
