### ISSUE TITLE
contract-standards: StorageManagement - discrepancy between NEP-145 and implementation

### ISSUE THREAD

**Issue by sept-en** [near/near-sdk-rs#425]
There's a function in `StorageManagement` trait: `storage_balance_of` [defined](https://github.com/near/near-sdk-rs/blob/001294b39aff972bb036b5fa66620d85004d27e3/near-contract-standards/src/storage_management/mod.rs#L58) as following:
`fn storage_balance_of(&self, account_id: ValidAccountId) -> Option<StorageBalance>;`

There's also the [implementation](https://github.com/near/near-sdk-rs/blob/001294b39aff972bb036b5fa66620d85004d27e3/near-contract-standards/src/fungible_token/storage_impl.rs#L31) for this in `FungibleToken` which returns `None` if the account does not exist.

According to the NEP-145 specs: 
`function storage_balance_of(account_id: string): AccountStorageBalance;`
> Used to lookup the account storage balance for the specified account. If the account is unknown to the contract then the total account storage balance returned will be zero.

So what's the right approach for this? Do we have a mismatch between NEP-145 specs and reference implementation?
Or was this changed somewhere in specs as well?

**Comment by evgenykuzyakov** [comment]
The standard is defined here: https://nomicon.io/Standards/StorageManagement.html#reference-level-explanation

**Comment by sept-en** [comment]
@evgenykuzyakov Thanks for pointing to this! I was referenced to figment and Github discussions as previously I was told that they contain the most up-to-date info.
