### ISSUE TITLE
Default blockchain interface in non-wasm environments and update interface

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#440]
Somewhat opinionated so open to discussion, but it makes more sense to me to have the `BlockchainInterface` set with some reasonable defaults so it doesn't require a user which doesn't override anything to build and set up the context and initialize the interface through `testing_env!`. If this is defaulted, the `BLOCKCHAIN_INTERFACE` could not be wrapped in an `Option` and thus remove a lot of confusing and unnecessary API usages.

Also, the current API only allows for replacing the interface completely, when it would be better to be able to just modify specific parts of the context on the initialized one. To keep changes somewhat minimal, can just expose a function that returns a mutable reference to the context initialized or just passing a function to apply a change on the context mutably.

One other thing that can possibly be done after this is changing the `BLOCKCHAIN_INTERFACE` from a `Box<dyn BlockchainInterface>` to just `MockedBlockchain` because after #417 there should be no need to have multiple interface types. This would simplify a lot of things, but is a breaking change.

Probably easiest if this is done after #417 comes in, as there will be conflicting changes and it would be simpler to do after.

**Comment by ilblackdragon** [comment]
May be instead just removing all this complexity via #373?

**Comment by austinabell** [comment]
> May be instead just removing all this complexity via #373?

Different problem, this issue is just relating to the testing framework and setting the `BLOCKCHAIN_INTERFACE` or whatever it is named to in the future is needed to setup the testing environment.

This issue is just relating to the unnecessary boilerplate needed for tests right now

**Comment by austinabell** [comment]
> [gov.near.org/t/revisiting-contract-testing-framework/2920](https://gov.near.org/t/revisiting-contract-testing-framework/2920) is related. If we are to disrupt our users with a new shiny testing framework, it probably makes sense to not also change existing ones.

Can you explain what specifically you are suggesting? What this issue suggests is not a breaking change for existing users, it just removes the *need* to have the boilerplate to be able to write unit tests.

I don't see this testing framework replacing unit tests, as it requires additional processes, so I'm wondering if you're saying to drop this issue or just to make sure there are no breaking changes?

**Comment by matklad** [comment]
Nothing specific, just the general observation that it looks like sandbox will eat a large part of "churn budget", so we need to be more conservative with test-related changes elsewhere. Even if sandbox supplements, rather than supplants, unit-testing, it's still will be perceived as "change to the way you write tests". 

Non-breaking changes are probably fine though!

**Comment by austinabell** [comment]
> Nothing specific, just the general observation that it looks like sandbox will eat a large part of "churn budget", so we need to be more conservative with test-related changes elsewhere. Even if sandbox supplements, rather than supplants, unit-testing, it's still will be perceived as "change to the way you write tests". 
> 
> Non-breaking changes are probably fine though!

Yeah what I'm suggesting allows for strictly less code, no different. Can also wait until after the next major release to do this, to make sure the changes are spaced out. That is definitely a good point that we should be cautious

**Comment by austinabell** [comment]
done
