### ISSUE TITLE
Simplify using BLOCKCHAIN_INTERFACE

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#441]
Currently using directly blockchain interface requires a bunch of weird code:

https://github.com/near/core-contracts/pull/148/files/7661aaa079271b37d8a871e5e4ce2a1035d8b1e9#diff-c242e2b31fefa6a6c09f7808e7ce9f0709353cff631d4e14eb3c993a5abf0f64R62

**Comment by ilblackdragon** [comment]
Potentially vis #373?

**Comment by austinabell** [comment]
Yeah, it's done through #417. The migration is pretty simple too, [ref-finance for example](https://github.com/austinabell/ref-contracts/commit/26ebf5b4ac12f45ba96dcd69ad11ca62c9cbf2b6), but this change is a breaking one and must come with a major release (along with other changes)

**Comment by ilblackdragon** [comment]
Nice, that looks like a great improvement.

**Comment by austinabell** [comment]
Closed through #417
