### ISSUE TITLE
Make `Base58PublicKey` an enum or struct which does not erase curve type and expose underlying bytes

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#447]
Currently, the curve type is deserialized and the curve byte is put as the first byte and the underlying `Vec<u8>` is exposed. There is no need to store the serialized format internally, instead of just keeping the curve and converting it to a vec for borsh serialization only.

**Comment by mikedotexe** [comment]
Recommended to go to @ChaoticTempest when there's bandwidth soon
