### ISSUE TITLE
Wasm binary does not correspond to the current version of the source code

### ISSUE THREAD

**Issue by telezhnaya** [near/near-sdk-rs#456]
While working on https://github.com/near/near-sdk-rs/pull/454, I found out that the binary for `examples/fungible-token` changes if I run `build.sh` in [the container](https://github.com/near/near-sdk-rs/tree/master/contact-builder).

I think we should check and rebuild all the binaries here and in `core-contracts` (maybe somewhere else)?

It would be also cool to set up CI that will build the binaries on the server and prevent merging the code to master if the binary does not correspond to the source code.

**Comment by ilblackdragon** [comment]
Let's include the build script inside container together with the repo to avoid issues like this. see https://github.com/ref-finance/ref-contracts/blob/main/ref-exchange/build_docker.sh for example

**Comment by austinabell** [comment]
wasm binaries are now tied to the code through CI check
