### ISSUE TITLE
Remove Base58PublicKey and replace PublicKey with that impl

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#462]
After #453, the alias of `PublicKey` to `Vec<u8>` can be replaced with the `Base58PublicKey` type so we don't need two types for the same functionality (one only for JSON serde impl).

cc: @ChaoticTempest https://github.com/near/near-sdk-rs/pull/453#issuecomment-871037521

**Comment by matklad** [comment]
Note that the right name for the thing is `PublicKey`, `Base58` prefix is not needed.
