### ISSUE TITLE
Update the container on DockerHub, add checks to CI

### ISSUE THREAD

**Issue by telezhnaya** [near/near-sdk-rs#465]
- [x] We need to update the container on DockerHub https://hub.docker.com/r/nearprotocol/contract-builder
New Dockerfile is here https://github.com/near/near-sdk-rs/blob/master/contract-builder/Dockerfile
This is required for https://github.com/near/core-contracts/pull/156 and https://github.com/near/core-contracts/pull/159
Please check that we will not break anything else by this change.

- [ ] We also need to add the check that the binaries correspond to code sources, at least in `examples` folder #461

**Comment by mikedotexe** [comment]
@chefsale do you have capacity to do this? I didn't notice it was assigned and we'd talked about @ChaoticTempest taking a look at this one.

**Comment by chefsale** [comment]
Yes, I already did the first part (pushed the docker image) and implemented the second check in core-contracts just will replicate the same thing here if I'm reading the second part correctly. @telezhnaya

**Comment by telezhnaya** [comment]
@chefsale yeah, it's the same task

**Comment by austinabell** [comment]
I needed something similar for something else I was doing, so I just finished this in #509

**Comment by chefsale** [comment]
Thanks for doing so, I assume we can close this one now @telezhnaya ? I forgot about it due to a bunch of other things 🥇

**Comment by austinabell** [comment]
> Thanks for doing so, I assume we can close this one now @telezhnaya ? I forgot about it due to a bunch of other things

The PR being merged will auto close this unless there is a reason for me to remove that comment from the PR

**Comment by telezhnaya** [comment]
Thank you, guys!
