### ISSUE TITLE
Assert contract errors in tests

### ISSUE THREAD

**Issue by nearmax** [near/near-sdk-rs#47]
We should have a way to assert error scenarios in smart contract tests without intercepting the panic. We could do it by removing `.unwrap()` in methods of `MockedBlockchain`, e.g. here: https://github.com/nearprotocol/near-bindgen/blob/master/near-bindgen/src/environment/mocked_blockchain.rs#L69 and instead add a hook that will be called on error.

**Comment by evgenykuzyakov** [comment]
It can be tested using `#[should_panic(expected = "...")]`, e.g. `#[should_panic(expected = "The new owner should be different from the current owner")]`
