### ISSUE TITLE
Log macro needlessly allocates

### ISSUE THREAD

**Issue by matklad** [near/near-sdk-rs#473]
Low priority, but this allocates String while it dosn't need to:

https://github.com/near/near-sdk-rs/blob/e4abb739ff953b06d718037aa1b8ab768db17348/near-sdk/src/utils/mod.rs#L34-L42

Sketch of an impl:

```rust
#[macro_export]
macro_rules! log {
    ($arg:tt) => {
        $crate::env::log($arg.as_bytes())
    };
    ($($arg:tt)*) => {
        core::write!($crate::LogFmt, $($arg)*)
    };
}

#[doc(hidden)]
pub struct LogFmt;

impl core::fmt::Write for LogFmt {
    fn write_str(&mut self, s: &str) -> std::fmt::Result {
        crate::env::log_str(s)
    }
}
```

**Comment by austinabell** [comment]
Correct me if I'm wrong, but your proposed suggestion would log each element individually instead of as one concatenated log. This would be unexpected and also be breaking because the formatting patterns wouldn't be valid anymore?

**Comment by matklad** [comment]
Ah, you are of course correct, this won't work, as our `log` isn't exactly equivalent to `print`: framing is important.
