### ISSUE TITLE
Create Rust helper functions interacting with RPC

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#482]
The approach detailed in the [current documentation](https://docs.near.org/docs/develop/contracts/sandbox) for the Sandbox uses `near-api-js` to deploy, call, and patch state to the Sandbox instance. While this is great, when it comes to Rust developers testing writing tests for their smart contracts, these interactions should also be available purely in Rust.

A shortlist of helper functions need to be created for the Sandbox. This list is not exhaustive:

- [x] Deploy a contract binary to an account
- [x] Change function call
- [x] View function call
- [x] Transfer native Ⓝ
- [x] Create subaccount
- [x] Delete account

(See other [Actions](https://nomicon.io/RuntimeSpec/Actions.html) for more ideas.)

**Note**: this interaction is going to be useful for the Sandbox, but we should keep in mind the possibility of having this be a crate in and of itself, at some point.

**Resources**: there is a fair amount of useful code that can be taken from [the Rust CLI](https://github.com/FroVolod/near-cli)

**Comment by ChaoticTempest** [comment]
Gonna close this one since it looks like we're gonna have other helper function tickets too, and all the helper functions listed here are implemented in https://github.com/near/sandbox-api
