### ISSUE TITLE
Provide downloadable Sandbox binary

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#484]
The Sandbox is a binary built from `nearcore` (read Epic for more detail) that is time-intensive to build.
Create downloadable Sandbox binaries that will work with Linux and Mac operating systems.

Note that `nearup` stores binaries in AWS S3 buckets:
https://github.com/near/nearup/blob/0a7e3e8f5ee525c68dbc9ad63cf0b40bc682477a/nearuplib/constants.py#L10-L16

This is an approach to consider.
@willemneal has also gone through effort to use IPFS for this. (There should also be a fallback in case IPFS has issues.)
This ticket includes the creation of these binaries, uploading, but also a longer-term solution such that this isn't manual in the future.
If the binaries can be taken from official releases of `nearcore`, that's great. If there can be instructions on how a user can validate a checksum, even better.

**Comment by mikedotexe** [comment]
Connecting this issue: https://github.com/near/near-ops/issues/555

**Comment by bowenwang1996** [comment]
How is this issue different from near/near-ops#555 ?

**Comment by mikedotexe** [comment]
Closing because it's captured in the linked issue above
