### ISSUE TITLE
Make HELP.md discoverable

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#505]
I was sure I reviewed some docs about `#[init]` and other attributes, but I had to google it to find the `HELP.md` file in the root of the project :man_facepalming:

**Comment by austinabell** [comment]
I think we could also word this issue as migrating the content from `HELP.md` into the respective sections of [the sdk docs](https://github.com/near/sdk-docs) as this high-level content probably lives better there. There might be some cases where the docs would be useful as rustdocs that this links to, but on a case-by-case basis.

**Comment by mikedotexe** [comment]
Let's definitely do this, adding it to our board.

**Comment by mikedotexe** [comment]
As a little history, we thought we could make this HELP.md file and contents show up in our Docs search, but cannot:
https://github.com/algolia/docsearch-configs/pull/4094#issuecomment-875356066
So let's putt it in the SDK Docs, getting a domain for it, and then revisit the Algolia ticket

**Comment by mikedotexe** [comment]
See this effort: https://github.com/near/sdk-docs/pull/37
