### ISSUE TITLE
[Discovery] Determine optimal I/O route for Sandbox

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#510]
As we grow out Sandbox testing, there may be concerns with tests that need to run from a "blank slate" or not retain changes from previous tests. Let's investigate the best way to do this.

Possible options:

- Use regular filesystem I/O
- Use virtual filesystem
- Consider "patch" command that resets state

**Comment by mikedotexe** [comment]
Will check with team during sprint planning, this may be invalid at this point, but am not sure.

**Comment by austinabell** [comment]
Being resolved in workspaces repo, and has working strategy now
