### ISSUE TITLE
`add_access_key` test coverage

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#516]
Noticed when making changes to these signatures that we have no usages or test coverage for this functionality. 

Ideally would be nice to have something close to an e2e test, but using the mocked blockchain should be sufficient just to make sure core functionality is correct and the API doesn't change unnecessarily.

This could test through a `Promise` initialization, and could test the `env` calls directly

**Comment by frol** [comment]
Resolved in #1029
