### ISSUE TITLE
NFT mint not payable

### ISSUE THREAD

**Issue by danielwpz** [near/near-sdk-rs#522]
hey, I'm wondering why is NFT `mint` not payable? Since it requires some deposit, why not make it payable?
https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L342

**Comment by austinabell** [comment]
> hey, I'm wondering why is NFT `mint` not payable? Since it requires some deposit, why not make it payable?
> [https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L342](https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs?rgh-link-date=2021-08-09T05%3A50%3A30Z#L342)

Hmm seems like you are correct here and is a bug in the standard. As a workaround, although not ideal, you can create a function that wraps this functionality and mark it as payable like the example does. I've opened #525 to fix this.

Thanks for the report!

**Comment by mikedotexe** [comment]
The purpose of having the `mint` function there was to show that a person can deviate from the standard and add their own methods in the `lib.rs` file that uses the `near_contract_standards`. I like your idea of having it payable. We'll bring this in

**Comment by austinabell** [comment]
> The purpose of having the `mint` function there was to show that a person can deviate from the standard and add their own methods in the `lib.rs` file that uses the `near_contract_standards`. I like your idea of having it payable. We'll bring this in

Actually, as I mention on the issue, I think that this method should just be removed from the trait and thus not exported by default. Because it's not part of the standard, but it can still be called from code if someone wants to create a function to wrap this functionality. What do you think of this @mikedotexe?

**Comment by danielwpz** [comment]
hey guys thanks for the quick reply.
I agree that we can keep the `mint` method here, just as a reference impl for others to use.

**Comment by austinabell** [comment]
> hey guys thanks for the quick reply.
> I would say that lets keep the `mint` method here, just as a reference impl for others to use. Given that it's already there and afaik there are a lot of developers already using it.

Addressed this point here https://github.com/near/near-sdk-rs/pull/525#discussion_r686920097. The mint logic will remain, this just doesn't expose a function by default that is not part of the standard. If you need a mint function, can do something like the [NFT example](https://github.com/near/near-sdk-rs/blob/cf3ef24ee51449b48a17246a5744a714e13f660b/examples/non-fungible-token/nft/src/lib.rs#L98).
