### ISSUE TITLE
`Account::new_unchecked()` performs checks?

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-sdk-rs#528]
I'd expect by the name `Account::new_unchecked` to not do any checks.

But it does in this line - https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/types/account_id.rs#L53

Is that a mistake?  Because it does the same thing as `AccountId::try_from`

**Comment by evergreen-trading-systems** [comment]
Ok I think I realise that in `release` mode, `debug_assert` will not run. So only runs during development.

**Comment by austinabell** [comment]
Yeah, it's just a method so that it will check during tests, but checking the validity of the account id will not be compiled into your contract. This is for those who are sure it will always be correct and want to skip the checks.

Is there anything that can be made more clear by docs?

**Comment by evergreen-trading-systems** [comment]
I had the same line of thought but overlooked the `debug!` macro. Definitely clear enough.
