### ISSUE TITLE
Add commit hook for styling

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#539]
I usually have fmt on save set in my IDE but when it fails and I only learn of this when my tests fail. In `npm` there are several easy to use commit hooks and I'm wondering if that would be a good solution here so that we don't waste CI time on failed formatting.

**Comment by austinabell** [comment]
> I usually have fmt on save set in my IDE but when it fails and I only learn of this when my tests fail. In `npm` there are several easy to use commit hooks and I'm wondering if that would be a good solution here so that we don't waste CI time on failed formatting.

Yeah, this is an option, but the hook can't run by default, it needs to be initialized manually by any contributor. Grin has one [here](https://github.com/mimblewimble/grin/blob/master/.hooks/pre-commit) as an example, but this is the only project I know off-hand that does this for a rust project.

**Comment by willemneal** [comment]
Aright sounds good to me.  It can be documented and we can keep the CI hook.  I mainly want it for myself as I've had this happen too often when the IDE silently fails to fmt.  

Also this from their contributing docs:

> When you make a commit, rustfmt will be run and we also automatically reformat the .rs files that your commit is touching.

Makes it sound like that hook will be used automatically, just not stage or commit the file.

**Comment by curryrasul** [comment]
> Dfkl

**Comment by uint** [comment]
Closed by #1078
