### ISSUE TITLE
Port the simulation tests from the FT example

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#541]
There's a repo in the `near-examples` for the fungible token. It uses simulation tests and stretches some functionality that would be useful to stress-test the Sandbox testing for Rust. 

[https://github.com/near-examples/FT/tree/master/tests/sim](https://github.com/near-examples/FT/tree/master/tests/sim)

**Comment by austinabell** [comment]
I'm not sure if I'm missing context but the example seems exactly like the one inside the sdk examples, what is the reason for having both?

**Comment by mikedotexe** [comment]
> I'm not sure if I'm missing context but the example seems exactly like the one inside the sdk examples, what is the reason for having both?

This is showing a standalone example. Ideally, this repo could be updated automatically when the `near-sdk-rs` example changes. This was decided a while ago because people wanted to have a lightweight version of common smart contracts like NFT and FT. The workflow that we'd tell someone in Discord might look like this otherwise:

1. Clone the Rust SDK
2. Copy the FT example from `examples/fungible_token/ft`
3. Go to crates.io and find the latest version of near-sdk-rs or something
4. Modify the `Cargo.toml` to not use relative paths but instead use that version
5. Now you have a standalone example.

We wanted these near-examples to have less steps.

**Comment by austinabell** [comment]
Tests were ported to js runner (exists in runner repo). Can close or wait until API is stabilized and then just copy tests over to this example repo
