### ISSUE TITLE
NFT standard: expose minimal usable interface

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#542]
Currently there are few functions that have full implementation but are dependent on `env` or assume some permissions and logic.

That is not the best way to implement these kind of standard contract implementations.

Instead there should be set of non assuming `internal_` methods that actually do the logic and leave the permissioning and composition to the user.

For example https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L347 `mint` method should be `internal_mint` that only does actual minting and only it. Everything else like assert/require and other stuff should be happening in usage code.

Also `internal_` are the methods that are not specified by standard but are the methods that everyone needs.

See FT standard implementation for example of `internal_register`, `internal_deposit`, `internal_withdraw`, which allow to create custom combinations easily.

Case in point from users of NFT standard: https://stackoverflow.com/questions/68800164/how-to-call-the-nft-mint-by-the-contract

There is also discussion around `mint` in #522, which given it should be internal method would not be useful - because it's not the method that directly gets exposed to the user.

**Comment by mattlockyer** [comment]
Agreed. I would really appreciate more "building blocks" standards implementations.

For reference of the issues facing devs, consider this example of implementing an NFT that shares metadata across a number of serialized tokens.

I attempted to leverage as much of the standard as possible, but ultimately led to a lot of copy paste.

https://github.com/near-apps/nft-series/blob/main/contract/src/lib.rs

**Comment by mikedotexe** [comment]
> Agreed. I would really appreciate more "building blocks" standards implementations.

I look forward to this, too. As a note, currently the Dev Platform team is not dedicating this quarter to hands-on work on the standards, which is different than how it was earlier this year. It will be up to folks in the community and not on this team to write NEPs. I've updated the NEP README to go over the best way to contribute to the standards. I believe the FT and NFT standards that are published provide guidance in how to contribute to these building blocks. Please let me know if we can meet up about this to provide additional context.

**Comment by mikedotexe** [comment]
Thanks, I think we should do a better job of documenting the functions that aren't in the standard (like minting) and live in the `lib.rs` file that uses the `near-contract-standards` crate. I should note that neither ERC-20 nor ERC-721 have mint in the standards, as this is something that contract developers will likely want to customize. (I believe this is also what you're stating.) I know @Daryl | NEAR has also wondered about this, and been concerned about the `nft_` prefix being used for any old function.
I'm having a hard time wrapping my head around whether these technically-optional methods (mint and burn) belong in a standard. Indexers would sure appreciate it, but unlike the other methods in the standards, we cannot dictate the required usage as specifically.
For instance, "burn" might mean "burn and remove from total supply" in one case, or "burn as in move to the owner account" in another. Or a total supply is forever set at initialization and there is no mint function.

**Comment by ilblackdragon** [comment]
> Thanks, I think we should do a better job of documenting the functions that aren't in the standard (like minting) and live in the lib.rs

That's not really the problem here. The problem is that this is a standard library not an example implementation.
Standard library should provide non assuming APIs that consumer code can combine in various ways.

There should be basic functions like `internal_withdraw`, `internal_deposit`, `internal_mint` that provide functionality that can be used to construct all the standards methods in one or two lines. So consumer code can customize that in various ways. Again, see FT implementation as an example and w-near contract as example of customization.

**Comment by mikedotexe** [comment]
Wrote a governance post suggesting a solution. Please feel free to weigh in.

**Comment by austinabell** [comment]
#572 moves towards this. I'll do a scan tomorrow to see if any other related changes can be done to make the nft standard more generally usable

**Comment by volovyk-s** [comment]
@austinabell looks like #572 is merged. Can we close this issue?
