### ISSUE TITLE
The implementation of 'Upgrade' of 'near-contract-standards' is NOT actually capable.

### ISSUE THREAD

**Issue by riversyang** [near/near-sdk-rs#544]
We have a standard implementation of `upgrade` feature for NEAR contracts, which is shown in `Upgrade` of `near-contract-standards`. But unfortunately, I found that it can NOT work for most cases actually.

For a very simple contract like:

```rust
use near_sdk::borsh::{self, BorshDeserialize, BorshSerialize};

use near_sdk::{env, near_bindgen, AccountId, PanicOnDefault};

near_sdk::setup_alloc!();

#[near_bindgen]
#[derive(BorshSerialize, BorshDeserialize, PanicOnDefault)]
pub struct SimpleContract {
    owner: AccountId,
}

#[near_bindgen]
impl SimpleContract {
    #[init]
    pub fn new() -> Self {
        assert!(!env::state_exists(), "Already initialized");
        Self {
            owner: env::signer_account_id(),
        }
    }
}
```

with a standard `Cargo.toml`:

```toml
[package]
name = "simple-contract"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "3.1.0"
near-contract-standards = "3.1.0"
```

The release version of wasm file of it will be about 1.6M bytes.

While interacting with NEAR network over json-rpc service, if we pass these bytes as a parameter of a function call to a contract, just like the `Upgrade` contract does, the parameter will be serialized to an integer array like `[98,34,156,34,234,......]` in the json string. This can be done by `near_sdk::serde_json` while using simulator or by `near-api-js`, which causes the length of serialized json string is larger than 5M bytes (over 3 times of the original length of the wasm file).

But in `nearcore`, the default value of `max_arguments_length` of `VMLimitConfig` is set to 4M. So we can NOT pass a byte array with the wasm code of a so simple contract like the above one, as the parameter `code` of the function `stage_code` of contract `Upgrade`.

I'm wondering whether this is a design issue of standard contracts, or there is a different way to use the `Upgrade` functionality?

**Comment by riversyang** [comment]
Sorry, it's my fault. I did NOT build project with environment setting `RUSTFLAGS='-C link-arg=-s'`. When use this flag, the size of the above wasm file reduces to about 100K bytes.

Theoretically, it is safe if the wasm file size is under 1M bytes. So the issue can be closed I think.

**Comment by austinabell** [comment]
You can also remove `rlib` from the crate type in `Cargo.toml`, unless you are using sim tests.

Happy to look into if some parts of the SDK you are using is causing a lot of bloat like this, let me know :)

**Comment by riversyang** [comment]
> You can also remove `rlib` from the crate type in `Cargo.toml`, unless you are using sim tests.
> 
> Happy to look into if some parts of the SDK you are using is causing a lot of bloat like this, let me know :)

Got it. Thank you.
