### ISSUE TITLE
Revisit nft_resolve_transfer args

### ISSUE THREAD

**Issue by mikedotexe** [near/near-sdk-rs#568]
According to the standard:
 [https://nomicon.io/Standards/NonFungibleToken/Core.html#nft-interface](https://nomicon.io/Standards/NonFungibleToken/Core.html#nft-interface)

`nft_resolve_transfer` has an argument `approved_account_ids` that is supposed to be `string[]` but I see there's a HashMap here. There's also a place where that field calls `approvals`, which should be fixed.

It seems like we don't need to pass the entire HashMap and can stick to the standard and just send a Vec<String> instead.

This is one of those tickets where I noticed it while I'm in the middle of something, so don't have more info other than this at the moment.

**Comment by austinabell** [comment]
What we probably want here is a Set (probably `BTreeSet`) for this. A set will serialize/deserialize as an array but comes with the property that we don't have to check for duplicates manually and can still do the lookup more efficiently than iterating through.

I had a quick look and still don't understand the use of storing an integer value for each one. I'll dig into this more tomorrow.

**Comment by austinabell** [comment]
dug slightly more into this, but it's clear there needs to be discussion around this because I need more context around what the flow is intended to be, and the fact that this is quite a breaking change so if the API is changed we need to be careful.

**Comment by frol** [comment]
Resolved in #1019
