### ISSUE TITLE
Does as_bytes have any cost?

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#579]
https://github.com/near/near-sdk-rs/blob/95954cad746502aeb64e42a8bd5bbbb1ce0df8cc/near-sdk/src/environment/env.rs#L358-L359

If `as_bytes` does have a cost, it seems that it is paid twice here and other places in this file.

**Comment by austinabell** [comment]
Nope, this will have no cost (I'm 98% sure in all cases). Can move these calls to above for peace of mind or readability, though

**Comment by willemneal** [comment]
Nah this is readable, just was wondering for my understanding.
