### ISSUE TITLE
refactor cross-contract examples

### ISSUE THREAD

**Issue by chadoh** [near/near-sdk-rs#589]
cross-contract-high-level and cross-contract-low-level each implement two different cool features:

1. Factory pattern: a method that creates a subaccount and deploys a contract to it, and even some proxy methods to interact with the subaccount via the factory (currently called `complex_call` and `simple_call`)
2. Merge sort: an implementation of the merge sort algorithm that powerfully demonstrates NEAR's asynchronous, concurrent cross-contract calls. 

Categorizing these examples by their _implementation_ rather than by their behavior leads to confusion for newcomers. I propose we instead create two new examples, "factory contract" and "merge sort." This has a couple benefits:

1. We can add a high-level and a low-level implementation to each. In the tests, we can loop through the wasm files for these two implementations and run the exact same set of tests, showing & ensuring the feature parity between the two implementations.
2. We can add more specific READMEs to these new projects explaining the significance of the pattern being demonstrated. We can target these READMEs at blockchain & comp-sci newbies who may not be familiar with factory patterns or the merge sort algorithm.

**Comment by nearmax** [comment]
cross-contract-high-level and cross-contract-low-level also demonstrate the following features:
* [Simple function call](https://github.com/near/near-sdk-rs/blob/master/examples/cross-contract-high-level/src/lib.rs#L119-L121);
* [Callback](https://github.com/near/near-sdk-rs/blob/master/examples/cross-contract-high-level/src/lib.rs#L122-L137);
* [Money transfer](https://github.com/near/near-sdk-rs/blob/master/examples/cross-contract-high-level/src/lib.rs#L139-L141);

Are we going to extract them into separate examples too?
