### ISSUE TITLE
Treat owned `self` receiver methods as state-machine transition

### ISSUE THREAD

**Issue by swfsql** [near/near-sdk-rs#614]
Currently methods that take owned `self` are seen as View calls that (without directly using `env` functions) wouldn't change the state, but this is a little bit weird because the method is acquiring total ownership of the state, and it can even create an `&mut` to it, so one could think that it could mean something similar to methods that take `&mut self`, as far as state changes goes.

My suggestion is to require methods that take owned `self` (or `mut self`) to return exactly `Self`, and use this result to update the state, similar to how `#[init]` does it. This would enable a state-machine transition pattern, where there would be no other outputs (besides promises being fired, without being returned).  

(This is just a vague suggestion, I haven't really tried to apply this pattern in practice)

**Comment by austinabell** [comment]
Going to close this issue for now, but if you'd like to continue discussion or have a way to make this work cleanly please feel free to re-open :)
