### ISSUE TITLE
Pagination of UnorderedSet GasLimitExceeded error

### ISSUE THREAD

**Issue by AngelBlock** [near/near-sdk-rs#626]
Pagination of UnorderedSet implemented for SputnikDao factory as .skip().take() of iter() https://github.com/near-daos/sputnik-dao-contract/commit/f5d4e611b4e08e3df21ad3b32ff048143cd04c02#diff-3dd4449e06b690d9a171047ec7a41be850335de5eaa66aa192a71ac7880c1e24R62 throwing the GasLimitExceeded error

Steps to reproduce: 

- currently deployed on sputnikv2.testnet

- run from index 500, with any limit >0 :

`near view sputnikv2.testnet get_daos '{"from_index": 500, "limit": 1}'`

- required 495+ records in the set to throw an error.

SDK docs are not suggesting any best practice way to paginate  UnorderedSet as per https://github.com/near/sdk-docs/blob/93e2fa29f3f38fc3870d404555cf843b765ac34a/docs/contract-structure/collections.md#pagination-with-persistent-collections

**Comment by evgenykuzyakov** [comment]
https://github.com/near/near-sdk-rs/blob/master/HELP.md#pagination-with-persistent-collections

**Comment by AngelBlock** [comment]
Many thanks, this approach is working.

**Comment by austinabell** [comment]
huh, I guess the nth iterator implementation for the old `Vector` isn't optimized. Looking at the code it seems that it would be and that nth would skip the previous. I might dig into this to see where it loses the skip functionality, maybe because of the `map` on the iterator.

Note, if anyone in the future is reading this, this only affects v1 of `Unordered` collections, not `near_sdk::store` ones

**Comment by austinabell** [comment]
> > huh, I guess the nth iterator implementation for the old `Vector` isn't optimized. Looking at the code it seems that it would be and that nth would skip the previous. I might dig into this to see where it loses the skip functionality, maybe because of the `map` on the iterator.
> > Note, if anyone in the future is reading this, this only affects v1 of `Unordered` collections, not `near_sdk::store` ones
> 
> Thanks for your reply and explanation, yes that would be useful for others to know, as I also noticed this implementation elsewhere (NFT I think).
> 
> When you say its only affects v1, did you mean that sdk v4+ will not have that issue? Thanks.

Yeah these are just pseudo versions, I just mean all new iterations of the collections are put under `near_sdk::store` and were introduced in 4.0 with unstable flag. It depends which data structure they use wrt this, but I will try to fix it for the old vector if possible when I have time
