### ISSUE TITLE
Add `#[must_use]` for `call!()` and `view!()` returns

### ISSUE THREAD

**Issue by swfsql** [near/near-sdk-rs#635]
Usages of `call!()` and `view!()` likely are being used in testing which can signal success and some failures. That signal likely should always be checked against, so a `#<span class="error">[must_use]</span>` attribute on those structures could help in identifying calls that are missing the check. 
 This would be a similar behaviour to the <span class="error">[`Result`]</span>([https://doc.rust-lang.org/src/core/result.rs.html#500](https://doc.rust-lang.org/src/core/result.rs.html#500)) type.

**Comment by austinabell** [comment]
sim tests deleted (this pattern is fixed in workspaces)
