### ISSUE TITLE
compilation error when contract returns `near_sdk` collection for unscoped public function

### ISSUE THREAD

**Issue by evergreen-trading-systems** [near/near-sdk-rs#660]
This compiles

```rs
pub(crate) fn a(&mut self) -> UnorderedSet<String> {
  panic!("")
}
```

This does not compile
```rs
pub fn a(&mut self) -> UnorderedSet<String> {
  panic!("")
}
```

**Comment by austinabell** [comment]
Can you please share the error message? This is almost certainly because when you have a public function annotated with `#[near_bindgen]`, if the function is public there will be code generation in this case to serialize the `UnorderedSet`. 

There is no default serialization for `UnorderedSet` because the values are lazily loaded from storage, so if you expect it to serialize in a specific way, you need to return some wrapper type where you implement the serialization format you need and load values from storage (which is expensive if the set is large).

**Comment by evergreen-trading-systems** [comment]
`the trait enums::_::_serde::Serialize is not implemented for UnorderedSet<String>`

That makes sense but I don't think that explains the behaviour between `pub` and `pub(crate)`. Only different is one is scoped and the other is unscoped. But both are public

**Comment by evergreen-trading-systems** [comment]
let me see if i get this. 

- `pub(crate)` makes it available to crate `A`. When compiled no outside module (`crate B`) has access. the subtle distinction is basically code is not generated for the function.
- `pub` same as above except code is generated and callable from outside module `crate B` 

ok makes sense

but still it doesn't make sense because even if code is generated or not (lazy eval or eager eval), the interface is still illegal. how does adding `(crate)` tell rust "hold up, it's ok, let this line compile even though it shouldn't" because it statically should not. 

have i missed something

**Comment by austinabell** [comment]
> let me see if i get this.
> 
> * `pub(crate)` makes it available to crate `A`. When compiled no outside module (`crate B`) has access. the subtle distinction is basically code is not generated for the function.
> * `pub` same as above except code is generated and callable from outside module `crate B`
> 
> ok makes sense
> 
> but still it doesn't make sense because even if code is generated or not (lazy eval or eager eval), the interface is still illegal. how does adding `(crate)` tell rust "hold up, it's ok, let this line compile even though it shouldn't" because it statically should not.
> 
> have i missed something

The difference is just in the semantics of our code generation with the `#[near_bindgen]` macro. If the method is `pub`, then code will be generated (and in this was where you found the error). Any other case, like `pub(crate) fn` or `fn` for example, there will be no codegen to expose the function to the wasm interface.

Some info here: https://www.near-sdk.io/contract-interface/public-methods although could be more complete
