### ISSUE TITLE
error[E0557]: feature has been removed

### ISSUE THREAD

**Issue by kulame** [near/near-sdk-rs#666]
```rust
 error<span class="error">[E0557]</span>: feature has been removed
 --> /home/kula/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmer-runtime-core-near-0.17.4/src/lib.rs:25:30

<div class="table-wrap"> 
</div>

25 | #!<span class="error">[cfg_attr(nightly, feature(unwind_attributes))]</span>

<div class="table-wrap">
  | ^^^^^^^^^^^^^^^^^ feature has been removed | 
</div>

 = note: use the C-unwind ABI instead

 Compiling jemallocator v0.3.2
 Compiling wasmer-vm v1.0.2
 error: cannot find attribute `unwind` in this scope
 --> /home/kula/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmer-runtime-core-near-0.17.4/src/typed_func.rs:617:37

<div class="table-wrap"> 
</div>

617 | #<span class="error">[cfg_attr(nightly, unwind(allowed))]</span>

<div class="table-wrap">
  | ^^^^^^ ... 862 | impl_traits!(<span class="error">[C]</span> S0,); | | --------------------- in this macro invocation ``` | 
</div>

**Comment by austinabell** [comment]
Can you please provide more info? This error isn't related to this repo so I'm not sure which versions or dependencies you are using.

If you have the repo this can be reproduced with, that would be ideal. If not maybe a small repro, Cargo.lock/toml, or some other info about what you are building would be appreciated

Can you also indicate which architecture you are building on?

Did this compile before and something has changed?

**Comment by kulame** [comment]
i upgrade my code 

https://github.com/kulame/cryptdao-contract

run 
cargo test. 
it show error message
```rust
error: cannot find attribute `unwind` in this scope
   --> /home/kula/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmer-runtime-core-near-0.17.4/src/typed_func.rs:734:37
    |
734 |                 #[cfg_attr(nightly, unwind(allowed))]
    |                                     ^^^^^^
...
887 | impl_traits!([C] S25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y);
    | ------------------------------------------------------------------------------------------------ in this macro invocation
    |
    = note: this error originates in the macro `impl_traits` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by austinabell** [comment]
> i upgrade my code
> 
> [kulame/cryptdao-contract](https://github.com/kulame/cryptdao-contract)
> 
> run cargo test. it show error message
> 
> ```rust
> error: cannot find attribute `unwind` in this scope
>    --> /home/kula/.cargo/registry/src/mirrors.tuna.tsinghua.edu.cn-df7c3c540f42cdbd/wasmer-runtime-core-near-0.17.4/src/typed_func.rs:734:37
>     |
> 734 |                 #[cfg_attr(nightly, unwind(allowed))]
>     |                                     ^^^^^^
> ...
> 887 | impl_traits!([C] S25, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y);
>     | ------------------------------------------------------------------------------------------------ in this macro invocation
>     |
>     = note: this error originates in the macro `impl_traits` (in Nightly builds, run with -Z macro-backtrace for more info)
> ```

I'm not running issues compiling this. Do you mind sharing your rust version with `rustc -Vv`? I'm suspecting this might just be an issue with using an old toolchain.

**Comment by kulame** [comment]
❯ rustc -Vv            
rustc 1.58.0-nightly (ad4423997 2021-11-14)
binary: rustc
commit-hash: ad442399756573dccacb314b6bf8079964bcc72a
commit-date: 2021-11-14
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0

**Comment by austinabell** [comment]
Do you still run into this issue? I wasn't personally able to repro in any way (with a similar setup). Our MSRV is currently 1.56, but it's possible that some deps are broken with specific combinations of versions.

I'll close this now, but please re-open if it was not resolved
