### ISSUE TITLE
Add event logs to NFT examples

### ISSUE THREAD

**Issue by telezhnaya** [near/near-sdk-rs#685]
We have new Events section in NEP-171 standard
https://nomicon.io/Standards/NonFungibleToken/Event.html

It would be cool to adjust our examples with it. We need to find a proper place for `log` statements.
We should log each `mint`, `transfer`, `burn` operation at the moment when we are more or less sure that the process would be finished successfully.

Random places where it may be placed:
https://github.com/near/near-sdk-rs/blob/master/examples/non-fungible-token/nft/src/lib.rs#L92
https://github.com/near/near-sdk-rs/blob/master/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L387

Contract creators struggle with it, we had a tg discussion about this few days ago: https://t.me/nearnft/1734

> Where are y’all putting your events for transferring? I had originally, naively, put the events in an internal transfer method that is called during nft_transfer and nft_transfer_call but I now realize that this will cause issues. My new thought was to put it at the end of nft_transfer and put it in nft_resolve_transfer. This will work for nft_transfer but for the nft_resolve_transfer I have an issue. I don’t know who the authorized_id is so if someone had called nft_transfer_call using the approval standard, I wouldn’t know  they were the ones that initiated the call.

**Comment by austinabell** [comment]
See #652 #627
