### ISSUE TITLE
Warn about `StorageKey` collisions

### ISSUE THREAD

**Issue by swfsql** [near/near-sdk-rs#704]
I'm not sure if this is already written somewhere, but as I don't remember seeing this, I thought about having this issue.

A contract that contains some fields can have it's `StorageKey` getting collided with other ones used internally by it's fields (ie. nft), and this could lead do data corruption. 
 For example, <span class="error">[this nft example]</span>([https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/examples/non-fungible-token/nft/src/lib.rs#L32](https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/examples/non-fungible-token/nft/src/lib.rs#L32)) contains a field `tokens` (which is a structure defined by the standard), and it also contains it's own <span class="error">[`StorageKey`]</span>([https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/examples/non-fungible-token/nft/src/lib.rs#L39](https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/examples/non-fungible-token/nft/src/lib.rs#L39)), but `tokens` can make use of another <span class="error">[`StorageKey`]</span>([https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L77](https://github.com/near/near-sdk-rs/blob/4399a86b3ffc303aea6f9b3808e7a4daa60bb087/near-contract-standards/src/non_fungible_token/core/core_impl.rs#L77)), also defined by the standard, for some operations.

This case that I linked is lucky because the first two variants of both `StorageKey` will always result in a different prefix for when creating the collections, but this could not be the case for other situations. To actually avoid this, the nft example could add as the first two variants of it's `StorageKey` to be paddings, so it would never be used and would always avoid collisions with the first two `StorageKey` variants that could be used by the field `tokens`. 

Another way of avoiding collisions would be for having a single `StorageKey`, and having all collections initializations (except for the `STATE` one) to be using distinct variants from that single `StorageKey`. But in order to do this, I believe that a manual check about every collection initialization inside of the code is necessary, including for methods related to the contract fields. 
 This would mean that every code that is meant to be used by other contracts should avoid defining it's own `StorageKey`.

So my suggestion would be for adding more information about this, possibly in places like in <span class="error">[near-sdk.io/contract-structure/nesting]</span>([https://www.near-sdk.io/contract-structure/nesting](https://www.near-sdk.io/contract-structure/nesting)).

**Comment by austinabell** [comment]
I believe https://docs.near.org/sdk/rust/contract-structure/nesting#error-prone-patterns and https://docs.near.org/sdk/rust/contract-structure/collections#error-prone-patterns should cover these points. Re-open if they don't!
