### ISSUE TITLE
Standards ownership ambiguity

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#705]
As mentioned in #627, there seems to be a "miscommunication" about who owns standards.

Does this mean the the NEP's and the example implementation here are considered the same?  Is the standards's crate in this repo not part of the sdk's purview?

**Comment by austinabell** [comment]
miscommunication was a bad word to use, was just indicating the delay in my review was just because I didn't want to step on anyone's toes. We have it figured out, no need for the issue
