### ISSUE TITLE
[near_contract_standards] TokenId should be aliased to the AccountId

### ISSUE THREAD

**Issue by SigismundSchlomo** [near/near-sdk-rs#706]
## Problem
In new versions of the SDK there is new, advanced AccountId type. TokenId type is still just type alias to the string.

## Proposed solution
TokenId should be type aliased to the AccountId

**Comment by willemneal** [comment]
According to the standard `TokenId` is just a string: https://nomicon.io/Standards/NonFungibleToken/Core.html#nft-interface

There is no requirement that it must be a valid account id.

**Comment by SigismundSchlomo** [comment]
Didn't saw it. So, it's okay. 
Thanks!
