### ISSUE TITLE
[EXT] Collections - LegacyTreeMap

### ISSUE THREAD

**Issue by near-arthur** [near/near-sdk-rs#710]
https://docs.rs/near-sdk/3.1.0/near_sdk/collections/struct.LegacyTreeMap.html

For each of the following functions, add an example code snippet:
* pub fn new
* pub fn len
* pub fn clear
* pub fn contains_key
* pub fn get
* pub fn insert
* pub fn remove

Examples should be simple, easy-to-follow, and useful to make onboarding and learning Rust SDK as straightforward as possible. See array primitive for examples of code snippet examples: https://doc.rust-lang.org/nightly/core/primitive.array.html), https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#784-790 for examples in code.

**Comment by austinabell** [comment]
Let's not document this, it is intended to be a deprecated structure and not worth putting in the effort to document.

This will be put behind a legacy feature or deprecated in this next version, and I will use this issue to track this also
