### ISSUE TITLE
UnorderedSet panics when removing existing value

### ISSUE THREAD

**Issue by pepsighan** [near/near-sdk-rs#733]
```
let mut set = UnorderedSet::new(b"a".to_vec());
set.insert(value);

println!("{}", set.len()); // Prints 0.
set.remove(value); // Panics with `attempt to subtract with overflow`.
```

The issue is probably arising from the len value being invalid.

**Comment by willemneal** [comment]
How are you using `const`? Also you aren't providing a prefix for the collection.

**Comment by pepsighan** [comment]
Sorry, JS habit. Fixed the code snippet.

**Comment by willemneal** [comment]
Is this done in a unit test or a contract method?

**Comment by pepsighan** [comment]
Contract method. Also, is this not reproducible on your end?

**Comment by pepsighan** [comment]
The issue was due to me not knowing how references in Rust work. Need to brush up on my Rust again.

**Comment by austinabell** [comment]
sorry I didn't respond until you closed, but I'd be curious to see the usage. Seems like you might have had multiple `UnorderedSet`s? I couldn't reproduce this myself

**Comment by pepsighan** [comment]
I was initially of the idea that `UnorderedSet` did not store the changes done to it. The specific way in which I was using it was: nesting an `UnorderedSet` within `LookupMap`. So, the actions in full that I was actually running:
1. Create a LookupMap and add an UnorderedSet within the map.
2. When changing the Set, I `get` the Set from the Map.
3. Make changes to the UnorderedSet.

This obviously did not work because `get` created a new UnorderedSet object which had nothing to do with the actual stored UnorderedSet.

As a fix, the additional step was required for the Set change to be recorded.
4. Re-add the UnorderedSet to the UnorderedMap.
