### ISSUE TITLE
Is there a way to get Near/USD exchange rate inside my smart contract?

### ISSUE THREAD

**Issue by siddharthborderwala** [near/near-sdk-rs#741]
I want to know if there is a way to get the exchange rate of Near/USD inside my smart contract using the rust sdk or another simple way without making network calls.

Thanks in advance. @ilblackdragon @mikedotexe

**Comment by siddharthborderwala** [comment]
@willemneal thank you for the information 🍻

**Comment by itegulov** [comment]
Seems to be answered, so closing this issue
