### ISSUE TITLE
Is there any plan about new collections

### ISSUE THREAD

**Issue by willser** [near/near-sdk-rs#744]
Hi,gays.I'm not sure if this question has been asked before, I searched and found no similar questions.

I am developing a new contract.I created a nested struct,it's like `UnorderedMap<AccountId,UnorderedMap<SomethingId,Something>>`.I noticed the `get` method of `UnorderedMap` be 
designed to `deserialize` all value to memory.So I guess if the second `UnorderedMap` of this struct is very big,there will be cost a lot of gas to read it(write it,too).

At first I thought there was something wrong with my code.But I didn't find another way in `source code` or `examples`.

So I open this issue to ask is there any plan about new collections?I think I need a nested collections in this case,it likes a table,I read a value by using two key.

**Comment by itegulov** [comment]
What do you mean by plan? If you are wondering when [these](https://github.com/near/near-sdk-rs/tree/master/near-sdk/src/store) collections will become available, then the answer is 4.0 stable release. But you can already try them out with 4.0 pre-releases if you enable `unstable` feature.

**Comment by willser** [comment]
> What do you mean by plan? If you are wondering when [these](https://github.com/near/near-sdk-rs/tree/master/near-sdk/src/store) collections will become available, then the answer is 4.0 stable release. But you can already try them out with 4.0 pre-releases if you enable `unstable` feature.

Accidentally press the enter 😂

**Comment by austinabell** [comment]
> Hi,gays.I'm not sure if this question has been asked before, I searched and found no similar questions.
> 
> I am developing a new contract.I created a nested struct,it's like `UnorderedMap<AccountId,UnorderedMap<SomethingId,Something>>`.I noticed the `get` method of `UnorderedMap` be designed to `deserialize` all value to memory.So I guess if the second `UnorderedMap` of this struct is very big,there will be cost a lot of gas to read it(write it,too).
> 
> At first I thought there was something wrong with my code.But I didn't find another way in `source code` or `examples`.
> 
> So I open this issue to ask is there any plan about new collections?I think I need a nested collections in this case,it likes a table,I read a value by using two key.

The get method of the example you gave will not deserialize all elements, it will just deserialize metadata about the structure. Only when it is used will it deserialize elements within the map.

As @itegulov mentioned, the API for nested structures is improved with the updated types under `near_sdk::store` which also have the benefit of not loading any single value more than once as they are cached in an intermediate layer.

**Comment by willser** [comment]
My bad,there is a mistake in my post.I read code in `near_sdk::store`,I think it will resolve my question,thank you for help.
