### ISSUE TITLE
build file is not generated 

### ISSUE THREAD

**Issue by ali2210** [near/near-sdk-rs#756]
Steps that I followed
cargo build --target wasm32-unknown-unknown --release
env 'RUSTFLAGS=-C link-arg=-s' cargo build --target wasm32-unknown-unknown --release

check ./build.sh it throw error no such file & directory Linux

**Comment by itegulov** [comment]
I am a bit confused here. Are you following this guide https://github.com/near/near-sdk-rs#building-rust-contract or are you trying to build your contract via https://github.com/near/near-sdk-rs#building-with-reproducible-builds? Just to be clear: you don't have to do both, so if the former way works for you and (if) you don't need reproducible builds, I suggest just sticking with that.

Let me know if you have any further questions.

**Comment by ali2210** [comment]
Thank you @itegulov
