### ISSUE TITLE
[EXT] NEAR SDK Descriptions

### ISSUE THREAD

**Issue by near-arthur** [near/near-sdk-rs#763]
https://docs.rs/near-sdk/4.0.0-pre.7/near_sdk/index.html

Some of the entries on this page are missing descriptions - short sentences describing the function.

For each of the following functions, add a description sentence:

- test_utils	
- utils
- RuntimeFeesConfig	
- VMConfig
- PromiseOrValue
- GCCount	
- IteratorIndex
- PromiseId	
- PromiseIndex	
- ProtocolVersion	
- ReceiptIndex
- ext_contract
- near_bindgen

**Comment by Buckram123** [comment]
Not sure how to describe GCCount and IteratorIndex, need some help.

**Comment by austinabell** [comment]
> Not sure how to describe GCCount and IteratorIndex, need some help.

Don't worry about those. Didn't realize those were exposed, I'll get around to deprecating them later

**Comment by r-near** [comment]
Closing as stale — many of the listed types (`GCCount`, `RuntimeFeesConfig`, `VMConfig`, `ProtocolVersion`) are no longer publicly exposed or have been renamed. Concrete doc gaps should be re-scoped against the current API.
