### ISSUE TITLE
[EXT] NEAR SDK - Init Example

### ISSUE THREAD

**Issue by near-arthur** [near/near-sdk-rs#766]
https://docs.rs/near-sdk/4.0.0-pre.7/near_sdk/attr.init.html

This function is missing an example.

Examples should be simple, easy-to-follow, and useful to make onboarding and learning Rust SDK as straightforward as possible. See array primitive for examples of code snippet examples: https://doc.rust-lang.org/nightly/core/primitive.array.html), https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#784-790 for examples in code.

**Comment by austinabell** [comment]
This will be deprecated/removed as it's not currently used. Thanks for catching :D

**Comment by NEARworld** [comment]
@austinabell 

If I remove `#[init]` macro, then the following error occurs
```rs
#[near_bindgen] // <-- line 48
impl Contract {
    /// Initializes the contract owned by `owner_id` with
    /// default metadata (for example purposes only).
    #[init]
    pub fn new_default_meta(owner_id: AccountId) -> Self {
```

```
error[E0277]: the trait bound `Contract: Serialize` is not satisfied
    --> src/lib.rs:48:1
     |
48   | #[near_bindgen]
     | ^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `Contract`
     |
```

So, it seems like I still need it..?

**Comment by austinabell** [comment]
> @austinabell
> 
> If I remove `#[init]` macro, then the following error occurs
> 
> ```rust
> #[near_bindgen] // <-- line 48
> impl Contract {
>     /// Initializes the contract owned by `owner_id` with
>     /// default metadata (for example purposes only).
>     #[init]
>     pub fn new_default_meta(owner_id: AccountId) -> Self {
> ```
> 
> ```
> error[E0277]: the trait bound `Contract: Serialize` is not satisfied
>     --> src/lib.rs:48:1
>      |
> 48   | #[near_bindgen]
>      | ^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `Contract`
>      |
> ```
> 
> So, it seems like I still need it..?

You don't remove this annotation, this just removes the unused proc macro annotation definition. Nothing changes from the contract level -- you just need to remove the `init` import if you had for some reason

**Comment by NEARworld** [comment]
@austinabell 
Oh I got it! thanks for your answer! very helpful !!
