### ISSUE TITLE
API Need: Promise with full receipt

### ISSUE THREAD

**Issue by TrevorJTClarke** [near/near-sdk-rs#772]
Currently promise support only covers the response `Vec<u8>` from callbacks.
 This is useful, but is missing critical other information available via RPC: logs array, gas used, etc per-receipt.

1.  1.  1.  Goal:
             Create/expose full receipt via <span class="error">[PromiseResult]</span>([https://docs.rs/near-sdk/4.0.0-pre.7/near_sdk/enum.PromiseResult.html](https://docs.rs/near-sdk/4.0.0-pre.7/near_sdk/enum.PromiseResult.html)) or similar in a way that contracts can consume logs/gas for the remainder of their function stack.

1.  1.  1.  Simple Use case:
             Say I want to paginate a list of accounts and call the maximum executions within the cap 300Tgas.
             If the contract were able to know how much gas was previously used overall (the top level txn gas), then the contract would know if it can continue paginating and avoid failure.
             Including access to logs, allows for additional conditional data available to the contract as well - imagine NFT event data coming back within an NFT transfer within a DAO proposal finalization. This could ultimately reduce cross contract calls drastically.

**Comment by TrevorJTClarke** [comment]
Here's more context:
`env::prepaid_gas()` only pertains to the gas within the context of current function execution - it doesnt know anything about the total available gas for the TXN as a whole. 
So going back to my example above, if you have a callback at any point in the stack, you have no idea how much gas was previously spent versus how much was (attached - used) accurately.

Quick example:
```
# Batch call with 300TGas
A. prepaid: 30TGas, Used Gas 0
   - 1. nested: prepaid 30TGas, used 10TGas
   - 2. nested: prepaid 15TGas, used 20TGas
```
I know these are fake numbers, but within each nested execution, there's no way to how much total gas is remaining so i know if I can keep calling more fns until full 300Tgas is used. Unless there's something missing to make that possible...

From the docs:
Used Gas: The gas that was already burnt during the contract execution (cannot exceed prepaid_gas)
source: [used_gas](https://docs.rs/near-sdk/latest/near_sdk/env/fn.used_gas.html) 

Prepaid Gas: The amount of gas attached to the call that can be used to pay for the gas fees.
source: [prepaid_gas](https://docs.rs/near-sdk/latest/near_sdk/env/fn.prepaid_gas.html)

In practice its more confusing than helpful.

**Comment by frol** [comment]
I think the presented use-case can be solved in a more elegant way using recently introduced yeild-resume features of NEAR Protocol: https://docs.near.org/blog/yield-resume

I am closing this issue as it is not actionable from SDK side. The discussion should start on the protocol side first:

* Chat: https://near.zulipchat.com/
* NEPs: https://github.com/near/NEPs
