### ISSUE TITLE
`AccountId::new_unchecked` is not unchecked in tests

### ISSUE THREAD

**Issue by encody** [near/near-sdk-rs#808]
I'm trying to generate an empty `AccountId` for use in tests, but due to [this debug assertion](https://github.com/near/near-sdk-rs/blob/master/near-sdk/src/types/account_id.rs#L54), the test always fails, because it cannot create the instance of the struct. It is not particularly intuitive that a function called `new_unchecked`:

1. Is not always "unchecked"
2. Changes its behavior depending on whether the environment is release or debug

I'm inclined to think that the presence of the word "unchecked" in the name of the method is enough warning to the author that the function could produce unexpected behavior, so I don't think this debug assertion is necessary.

**Comment by austinabell** [comment]
Yes, this was intentional to be able to catch any potential bugs without having a cost when compiling the binary for release.

What would be the motivation for having a truly invalid account id? Seems like a bad practice (which is why it is nudged against)

**Comment by encody** [comment]
We have a use-case for delete-able NFTs. Since a "delete NFT" event doesn't exist, we're instead emitting a transfer event with the recipient account ID set to an empty string, so that the NFT will not be indexed under a real account. It was assumed this was preferable to transferring the NFT to some sort of trashcan account.

**Comment by willemneal** [comment]
Why not emit a burn event and then delete the NFT from the contract state?  Is there a reason to keep it around?

**Comment by ryancwalsh** [comment]
@sccheruku, thanks for pointing out that https://github.com/near/near-sdk-rs/issues/528 is a related issue, and I'm adding you here so that you're in the loop.

**Comment by encody** [comment]
@willemneal Thanks, I don't know how I missed that.

Regardless, that doesn't fix the `new_unchecked` function. If it is decided that no legitimate motivation for using the function could exist, why does it exist?

**Comment by austinabell** [comment]
> @willemneal Thanks, I don't know how I missed that.
> 
> Regardless, that doesn't fix the `new_unchecked` function. If it is decided that no legitimate motivation for using the function could exist, why does it exist?

The motivation is that there is no cost for using it when building for release. Debug asserts are common to prevent bugs in testing so that larger issues don't happen when used in production.

The motivation is that this check is short-circuited because the account id validation happens within the near runtime.

**Comment by austinabell** [comment]
Going to close this, but if anyone has anything to add to this we can open it back up
