### ISSUE TITLE
Remove status-message-collections and merge with status-message

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#809]
Actually never realized this example exists. Should prob migrate to one contract and remove the bloat that currently exists (like why there is a `LookupSet` in collections that is completely unused)

The API should be the same as what exists within `status-message`, so the factory-contract example that uses this won't break

**Comment by shariffdev** [comment]
Hey, I made a PR on this here, https://github.com/near/near-sdk-rs/pull/1076
I also could not find any places where the `status-message-collections` was being used in the factory-contract.

**Comment by uint** [comment]
> Hey, I made a PR on this here, #1076 I also could not find any places where the `status-message-collections` was being used in the factory-contract.

I'm confident the intention here is to have one contract called `status-message` that uses a `LookupMap` under the hood.

I believe @austinabell assumed the current `status-message` contract would be deleted and then `status-message-collections` would be renamed to `status-message` and adapted, but it shouldn't matter much which angle you tackle this from.

**Comment by uint** [comment]
Closed by #1076
