### ISSUE TITLE
Export basic types directly instead of vm-logic

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#81]
Currently basic types like BlocmHeight used inside Bindgen but also client contracts need also import them from near-vm-logic 
 It's very confusing and adds extra dependency that can be misaligned (like right now with crate.io having 0.4.4 whereas Bindgen depended on 0.4.3).

Ideally Bindgen should just export these types itself and client contracts don't need to depend directly on near-vm-logic.

**Comment by nearmax** [comment]
Moving to Backlog and assigning P2 since we will be cleaning up near-bindgen soon anyway.
