### ISSUE TITLE
Update nearcore crates to include new function call weight

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#813]
Needed for unit and sim tests. Updating this slipped my mind. There was also a refactor with that change that cuts the amount of code we need and makes unit tests match the actual runtime execution.

@miraclx do you still handle the releases for internal crates?

It's a quick change to make on the SDK and I will do this.

**Comment by miraclx** [comment]
Yes, `0.13.0` is planned for the end of the month, do you need it sooner than that?

**Comment by austinabell** [comment]
Closed with #820
