### ISSUE TITLE
Const-generics feature on a borsch dependency

### ISSUE THREAD

**Issue by curryrasul** [near/near-sdk-rs#827]
Why not to enable const-generics feature on a borsch dependency ? I think it'll be very useful.

**Comment by austinabell** [comment]
> Why not to enable const-generics feature on a borsch dependency ? I think it'll be very useful.

Const generics was previously below the MSRV of the SDK but that is no longer the case. I'll open up a PR. 

You could always enable it on whatever crate you are using, there isn't really a requirement here, is there?

**Comment by curryrasul** [comment]
> You could always enable it on whatever crate you are using, there isn't really a requirement here, is there?
I think the only way to enable this feature from borsch is to include borsch as a dependency separately to my project and use it for serialization, not the near-sdk's borsch re-export. Would be better to use it right away.

Did I understand you correctly ?

**Comment by austinabell** [comment]
> > You could always enable it on whatever crate you are using, there isn't really a requirement here, is there?
> 
> I think the only way to enable this feature from borsch is to include borsch as a dependency separately to my project and use it for serialization, not the near-sdk's borsch re-export. Would be better to use it right away.
> 
> Did I understand you correctly ?

Yes, but you don't need to even use borsh directly, simply bringing borsh in with the feature:

```toml
near-sdk = "4.0.0"
borsh = { version = "0.9.3", features = ["const-generics"] }
```
will enable it for the SDK. Since features in Rust should be additive, it uses the same dependency with the feature enabled. Can check by doing something like:

```rust
near_sdk::borsh::to_vec(&[0u8; 1033233]).unwrap();
```

And it will work if you enable the feature
