### ISSUE TITLE
near_contract_standards NFT enumeration extension

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-sdk-rs#842]
In near_contract_standards **NonFungibleTokenEnumeration Extension**, this help method **enum_get_token** use **unwrap** directly may cause panic due to **None** value when **TokenMetadata Extension** and **Approval Extension** are not implemented. （**token_metadata_prefix** and **approval_prefix** are **None** when new NonFungibleToken）

[<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/95295094/174247270-66ffbae8-970a-43a4-b9be-b9d0136cfec8.png)</span>](https://user-images.githubusercontent.com/95295094/174247270-66ffbae8-970a-43a4-b9be-b9d0136cfec8.png)

**Comment by austinabell** [comment]
yes, this is strange. Not quite sure the motivation for why this was done like this.
