### ISSUE TITLE
Confusing measure storage in NonFungibleToken

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-sdk-rs#844]
1.tokens_per_owner calculate twice 2.Did not remove tmp_token_id from UnorderedSet when roll back [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/95295094/174286829-81372e27-0930-459e-8114-555c962adff7.jpeg)</span>](https://user-images.githubusercontent.com/95295094/174286829-81372e27-0930-459e-8114-555c962adff7.jpeg) [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/95295094/174286848-984a2246-f340-4918-a893-d095dd7dac3a.png)</span>](https://user-images.githubusercontent.com/95295094/174286848-984a2246-f340-4918-a893-d095dd7dac3a.png)

**Comment by austinabell** [comment]
You're absolutely right about this, and also noting that at the end, the `tokens_per_owner` removal check is redundant, so there is that to change, too.

...and a few other things to be updated.

Thanks for pointing out
