### ISSUE TITLE
Some questions about new Cross Contract Call

### ISSUE THREAD

**Issue by hanakannzashi** [near/near-sdk-rs#847]

**Comment by hanakannzashi** [comment]
default with_unused_gas_weight is 1, it means every cross contract method get more gas than static_gas for them, if we call the method with enough gas, that is OK, because static_gas + unused_gas is enough, but if we call the method without enought gas, static_gas + unused_gas may not enough either, it will cause panic in cross contract call. So whether panic is uncertain, this is very bad. If this cross contract method is a callback, we hope it won't panic at any time.

**Comment by austinabell** [comment]
> default **with_unused_gas_weight** is 1, it means every cross contract method get more gas than **static_gas** for them, if we call the outside method with enough gas, that is OK, because **static_gas + unused_gas** is enough, but if we call the outside method without enought gas, **static_gas + unused_gas** may not enough either, it will cause panic in cross contract call. So whether panic is uncertain, this is very bad. If this cross contract method is a callback, we hope it won't panic at any time.

yes, the amount of gas that will be distributed by weight will be relative to the amount attached, but this is purely additive from specifying static amounts which previously existed. You have the right intuition that specifying a sufficient static gas for callbacks is important, but this new API allows you to utilize gas more efficiently without sacrificing control.

Did I understand what you are asking for more context about?
