### ISSUE TITLE
Remove requirement of Error type being `JsonSchema` for `#[handle_result]` errors

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#853]
<pre> #<span class="error">[handle_result]</span>
 pub fn foo() -> Result<(), anyhow::Error> 

 { Err(anyhow::anyhow!("test")) } 

</pre>

and error is:

 error<span class="error">[E0277]</span>: the trait bound `anyhow::Error: JsonSchema` is not satisfied
 --> src/lib.rs:11:1

<div class="table-wrap"> 
</div>

 11 | #<span class="error">[near_bindgen]</span>

<div class="table-wrap">
  | ^^^^^^^^^^^^^^^ the trait `JsonSchema` is not implemented for `anyhow::Error` | 
</div>

Not sure yet if the codegen isn't working, because I thought the `Ok` type was being extracted for this.

cc @itegulov

**Comment by itegulov** [comment]
Oh, yeah, I have added a special case for `#[callback_result]`, but not for `#[handle_result]`. Will fix.
