### ISSUE TITLE
How to erase a contract previously initialised ?

### ISSUE THREAD

**Issue by GaloisField2718** [near/near-sdk-rs#864]
Hello, 
I often have this error : 
https://github.com/near/near-sdk-rs/blob/41eb838b0d745394d7530aabe363f80dfc649a0c/near-sdk-macros/src/core_impl/code_generator/impl_item_method_info.rs#L220.
I want to understand how to erase a contract to deploy and initialise a new one from zero (to hero ;) ).
Especially I want to see if it's possible to not create a new address to deploy and initialise a new contract, hence my question :)

**Comment by miraclx** [comment]
Check this out: https://github.com/near/core-contracts/tree/master/state-cleanup

**Comment by GaloisField2718** [comment]
Thank you very much ^^

**Comment by austinabell** [comment]
https://www.near-sdk.io/upgrading/prototyping has some suggestions as well you can check out
