### ISSUE TITLE
Failed promise result not visible in callback

### ISSUE THREAD

**Issue by veigajoao** [near/near-sdk-rs#865]
When dealing with callbacks, it is possible to access the env::promise_result context.

This call returns an enum:
```
pub enum PromiseResult {
    NotReady,
    Successful(Vec<[u8]>),
    Failed,
}
```

Per the documentation, NotReady is never returned in the current version.

Successful is returned when the cross contract call is executed without panicking and the return value of the call is present in the enum variant as a vector of bytes.

However, when a transaction fails (Failed variant) there is no information regarding the error type returned, all that is accessible through the smart contract is the information that the call has failed.

I know that it is perfectly possible to fetch the panic message by checking the transaction from outside of the blockchain. Is there a way to also check the panic message during the execution of the callback? So that the contract can have different reactions based on the error message?

**Comment by austinabell** [comment]
Unfortunately, this data is not accessible by the protocol/runtime. I'm not sure the context of why it isn't, I assume it's to keep a small data footprint not to have to transfer the failure message data across shards by default, but that's just a guess.

@bowenwang1996 do you have context on this, or would know who does?

**Comment by pmarangone** [comment]
Any news on this? Our protocol interacts a lot with other contracts and not having access to what kind of error we are at leads to more complexity in the contract

**Comment by frol** [comment]
[Protocol community chat](https://near.zulipchat.com/#narrow/stream/295306-contract-runtime/) is the best place to discuss it. This issue is not actionable without a protocol change, so I am closing this issue. Feel free to discuss and open a tracking issue on nearcore repo.
