### ISSUE TITLE
Any reason why core_impl in the macro's is not public?

### ISSUE THREAD

**Issue by willemneal** [near/near-sdk-rs#866]
https://github.com/near/near-sdk-rs/blob/11f60860fd6c34e9d27f37bb1ff9930c2aaa42e3/near-sdk-macros/src/lib.rs#L9

**Comment by austinabell** [comment]
Yeah, those aren't meant to be public. Exposing them would be too large of an API surface to maintain without breaking changes. If you need any of these things, I would just copy over what you need.
