### ISSUE TITLE
Json event log for nep141 missing

### ISSUE THREAD

**Issue by telezhnaya** [near/near-sdk-rs#883]
https://explorer.near.org/transactions/9USp26GEi2WGf5nHoctL53adsSN5vm7MLgNcQDbrNGfX#Emk6L18YeRbPrHvCxbrDcdHV5XKp83JobaiBcjWGijhS

I see event log at ft_transfer_call, but there's no log at ft_resolve_transfer. So, for the indexer, transfer looks successful. 
While, if we ask the contract for the balance, it doesn't change.

**Comment by frol** [comment]
I feel that it is a bug in the token.paras.near implementation, and not in near-sdk-rs. It feels like they indeed have a bug in JSON EVENTS standard implementation 😨

**Comment by austinabell** [comment]
hmm, yeah, seems like the standards emits the event on both https://github.com/near/near-sdk-rs/blob/1607d0d4fe17dd186a4657b5049c26a74515559c/near-contract-standards/src/fungible_token/core_impl.rs#L104 so unless I'm missing some edge case, that would just be a bug in a specific implementation they have

**Comment by frol** [comment]
@telezhnaya I believe they actually used near-sdk-rs 4.0.0-pre.6 version which had only a half-baked Events support 😞 

https://github.com/near/near-sdk-rs/blob/0e89031054b43d7dd96fe64d85863efc8f202e46/near-contract-standards/src/fungible_token/core_impl.rs

As you can see, there are already transfer events, but refunds were still only generating text logs.

I am closing this issue as the bug has been already fixed on the near-sdk-rs side of things.
