### ISSUE TITLE
#[private] macro not performing assertion in unit tests

### ISSUE THREAD

**Issue by veigajoao** [near/near-sdk-rs#902]
I'm currently testing a contract method decorate with #[private] macro.

In unit tests I'm building the mocked context with:
- predecessor_account_id: user.testnet
- current_account_id: contract.testnet

Yet the method executes and does not throw the expected "Method [...] is private".

However, if I manually implement the assertion:
```
if near_sdk::env::current_account_id() != near_sdk::env::predecessor_account_id() {
        near_sdk::env::panic_str("Method my_method is private");
}
```
Then the test throws the expected error.

I suppose there is some kind of issue with using the #[private] method in unit tests. When I deploy the contract to testnet and attempt to call the private method directly it throws the expected error.

Does anyone have more information regarding this error?

**Comment by willemneal** [comment]
The issue here is the compilation target.  When compiling unit tests, it uses your local machine, however, in the macro's code it only generates the checks if targeting wasm. I personally think that unit testing in wasm is better and there is some work on that, but for anything other than internal logic tests, I would use [workspace-rs](https://github.com/near/workspaces-rs) for testing contract interactions.

**Comment by veigajoao** [comment]
Now it makes sense, thanks for the explanation. Regarding testing in wasm, is there a specific setup to do it using the NEAR sdk? How would it be performed?

**Comment by austinabell** [comment]
Unfortunately not, compiling to wasm means we can't mock the NEAR runtime host functions (for it to be functional on-chain). There is some discussion of how this could happen in #467, but this still involves a pattern similar to `workspaces` but just with less overhead.

It would be too much of a side effect if the codegen added the check within the inner function and not the exposed function. The codegen looks something like:

```rust
#[cfg(target_arch = "wasm32")]
#[no_mangle]
pub extern "C" fn some_method() {
    // ... omitted
    if near_sdk::env::current_account_id() != near_sdk::env::predecessor_account_id() {
        near_sdk::env::panic_str("Method method is private");
    }
    let mut contract: MyContractStructure = near_sdk::env::state_read().unwrap_or_default();
    contract.some_method();
    near_sdk::env::state_write(&contract);
}
```

And shifting the check inside the `some_method` means it can't be called directly from another function in some contexts. I suppose all of these patterns and assumptions can be better documented. https://docs.near.org/sdk/rust/contract-structure/near-bindgen currently has some information on this, but it can be improved.

**Comment by agostbiro** [comment]
Thanks for all the input in this issue! I'm closing it as fixed, but please feel free to reopen if any concerns are remaining.
