### ISSUE TITLE
No compiler error for using `Result` with init

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#926]
Currently, any method that has `Result` as a return is given a compiler error, signposting toward `#[handle_result]`. The issue is that `#[init]` methods (as well as possibly others) don't emit this same error.

This is a footgun that someone hit from the ecosystem and the error is cryptic because it uses a serialized `Result` as the state. 

Unsure if we can safely enforce that the return type serialized is `Self`

cc @itegulov

**Comment by itegulov** [comment]
Yeah I also caught this while working on https://github.com/near/near-sdk-rs/pull/890, should be fixed after we merge it (at least in some form)

> Unsure if we can safely enforce that the return type serialized is Self

Also was contemplating this while working on #890, but to me it seems like init functions should not be restricted just to `Self`. *Technically* you can initialize the contract state with whatever stuff you want, not sure if there is a legitimate pattern for it (maybe writing a superset of contract state if you know you will need this extra data later when you upgrade or something?). Some people might also refer to contract by its literal name as opposed to `Self`, also I imagine there are even weirder corner cases with typedefs and other stuff, so probably not worth to mess with this.
