### ISSUE TITLE
Optimize `TreeMap` range query implementation

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#928]
`TreeMap` is awkward to use as its range query complexity is `O(Klog(N))`, which means iterating it is very costly. This happens because `tree_map::iter::Keys` holds a bounded range defining the iterator elements, but not their position in the tree:

```rust
pub struct Keys<'a, K: 'a>
where
    K: BorshSerialize + BorshDeserialize + Ord,
{
    tree: &'a Tree<K>,
    length: u32,
    min: Bound<&'a K>,
    max: Bound<&'a K>,
}
```

So every time we search for the next (or previous) element in the tree we have to search it from the top of the tree:
```rust
fn next(&mut self) -> Option<&'a K> {
    ...
    let next = next_asc(self.tree, self.min);
    ...
}

fn next_asc<'a, K>(tree: &'a Tree<K>, bound: Bound<&'a K>) -> Option<&'a K>
where
    K: BorshSerialize + Ord + BorshDeserialize,
{
    match bound {
        Bound::Unbounded => tree.min(),
        Bound::Included(bound) => tree.ceil_key(bound),
        Bound::Excluded(bound) => tree.higher(bound),
    }
}
```

This does not have to be the case, the range query can be answered in `O(K + log(N))` if we were to save the actual bounding tree nodes and find the next (or previous) element in `O(1)` (amortized). This cannot be easily done with the current implementation however as there is no way to traverse up to the parent for a given node. So a decent refactoring is required, but we could actually avoid storing the parent index in the `Node` struct if we hold a `cur_path: Vec<FreeListIndex>` in the iterator instead (i.e. a list of node indices we have gone through to reach the current node).

Part of #818

**Comment by askoa** [comment]
Is this still required? Can I take a stab at it?

**Comment by itegulov** [comment]
@askoa yes, this is still very much needed. I don't think anyone is working on this so feel free to take a stab at this if you would like!

**Comment by itegulov** [comment]
Nah, just the std vector is fine. No reason to make iterator persistent on the trie, I don't see how that would be a benefit.
