### ISSUE TITLE
rustc-agnostic `contract-builder` image

### ISSUE THREAD

**Issue by itegulov** [near/near-sdk-rs#935]
Opening in this repo for the lack of a better public place.

We should consider making our `contract-builder` image agnostic of the rustc version installed inside of it.  With the introduction of cargo-near, we would have to support a matrix of image versions (`contract-builder:latest-1.56.1-0.2.0`, `contract-builder:latest-1.61.0-0.3.0` etc). Since ABI records the rustc version, cargo-near version, and docker image as a part of the metadata, we should be able to reproduce the build even if the docker image does not have the rustc/cargo-near installed inside. We could even consider using general-purpose images as opposed to our ones (i.e. `ubuntu:latest` vs `contract-builder:latest`).

On the other hand, this might complicate onboarding as the docker image will no longer be a ready-to-go solution.

CC @austinabell

**Comment by frol** [comment]
We will move it to SourceScan. See cargo-near PR for more details: https://github.com/near/cargo-near/pull/134
