### ISSUE TITLE
Doc strings are lacking in promise.rs

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-sdk-rs#94]
There are no explanation for the arguments and their types in promise.rs for all the methods.

For example `add_access_key` takes `method_names` as `Vec<u8>` but examples are presented as strings. Also doesn't cover the case of empty string for allowing all methods to be called.

Having doc strings with per-argument types and explanations of arguments would be great for developers to understand.

**Comment by frol** [comment]
It is now resolved: https://docs.rs/near-sdk/latest/near_sdk/struct.Promise.html#method.add_access_key_allowance
