### ISSUE TITLE
Enable API around borrowed AccountId

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#944]
The current API forces allocations for `AccountId` and can be annoying to deal with in certain cases with lifetimes. We could build an API, similar to https://doc.rust-lang.org/nightly/std/path/struct.Path.html vs https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html semantics to allow referencing and validating account ID strings without allocating and taking ownership.

Roughly, the structs would look like:

```rust
pub struct AccountId(String);

pub struct AccountIdRef<'a>(&'a str);
```

> Alternatively could be `AccountId` and `AccountIdBuf`, but this would be more breaking from current APIs

Which can be much more flexible in cases where you never need an owned value because you don't need to create a binding to that value, you can just reference some static string or something with an adequate lifetime.

An extension of this is that we could build a macro to alleviate the construction and have the account id validation happen at compile time rather than being forced to do at runtime.

**Comment by uint** [comment]
I pulled the "extension" part into a new issue: #1061

**Comment by frol** [comment]
Closing in favor of #1105
