### ISSUE TITLE
VMContextBuilder seems to not support block_timestamp_ms

### ISSUE THREAD

**Issue by 0xantman** [near/near-sdk-rs#953]
It seems like VMContextBuilder is not supporting timestamps in ms.

When trying to build the testing_env with a custom timestamp `context.block_timestamp(100).build()` the VM work well with `env::block_timestamp()` showing `100` but `env::block_timestamp_ms()` still show `0`

**Comment by austinabell** [comment]
What would you have expected here? `block_timestamp` is in `ns`, and `100` is 0 ms (rounded down) since 1 ms = 1,000,000 ns.

I believe this is working as intended, but I'll leave open in case there is a detail I am missing

**Comment by 0xantman** [comment]
Oh that's right sorry for the confusion, I will close the issue. Thank you
