### ISSUE TITLE
NFT `nft_resolve_transfer` does not match NEP (`approved_account_ids` != `approvals`)

### ISSUE THREAD

**Issue by frol** [near/near-sdk-rs#967]
I noticed it while reading NEP-188, and here is my summary of this problem: https://github.com/near/NEPs/pull/188#discussion_r1028154515

https://github.com/near/near-sdk-rs/blob/a903f8c44a7be363d960838d92afdb22d1ce8b87/near-contract-standards/src/non_fungible_token/core/resolver.rs#L29-L40

<img width="781" alt="image" src="https://user-images.githubusercontent.com/304265/203089013-6c629096-24ed-4bd1-89f2-5a35477d7d39.png">

https://nomicon.io/Standards/Tokens/NonFungibleToken/Core

**Comment by austinabell** [comment]
hmm, that is a strange inconsistency to have. I don't know the context behind this or if there was a reason for this to be the case.

Sounds like this should change within the implementation, but this is a silently breaking change. I've added this to the list in #918, as this should absolutely be explored when that happens.

**Comment by frol** [comment]
Resolved in #1019
