### ISSUE TITLE
Deprecate/remove upgrade standard

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#969]
Afaik, there is no usage of this, and it's unclear this is the interface that should be considered a standard. I noticed this was something that existed during #968 

Likely this gets removed with #918 or deprecated in next major release?

**Comment by itegulov** [comment]
Haven't we already deprecated it in https://github.com/near/near-sdk-rs/pull/856? We can remove it for sure though.

**Comment by austinabell** [comment]
Yup, I have a terrible memory, I forgot I did this. I'll just keep a point in the rewrite to not include this
