### ISSUE TITLE
ABI generation fails with `Self` return types

### ISSUE THREAD

**Issue by miraclx** [near/near-sdk-rs#972]
```rust
#[near_bindgen]
impl MyType {
    pub fn new() -> Self { ... }
}
```

```console
$ cargo build --features near-sdk/__abi-generate
   Compiling adder v0.1.0 (/Users/miraclx/git/near/near-sdk-rs/examples/adder)
error[E0411]: cannot find type `Self` in this scope
 --> src/lib.rs:3:12
  |
3 |     pub fn new() -> Self {
  |            ---      ^^^^ `Self` is only available in impls, traits, and type definitions
  |            |
  |            `Self` not allowed in a function

For more information about this error, try `rustc --explain E0411`.
error: could not compile `adder` due to 2 previous errors
```

**Comment by itegulov** [comment]
Is there a common use for `Self` outside of `init` functions though? Your particular example works if you mark the function with `#[init]`.

**Comment by austinabell** [comment]
> Is there a common use for `Self` outside of `init` functions though? Your particular example works if you mark the function with `#[init]`.

Not a common one, but I think it is a valid one. I've seen devs try this, and it only doesn't really work when there are storage collections in the state. But if everything is in-memory and you just want to return all of the state, there could be a reason to do so.

`new` might be a confusing naming for the use case, though.

To confirm, this fails also, right?

```rust
#[near_bindgen]
// derive default, serde, ....
struct MyType {
  data: u8,
}

#[near_bindgen]
impl MyType {
  pub fn get_state(self) -> Self { self }
  // or
  pub fn get_state(&self) -> &Self { self }
}
```

**Comment by itegulov** [comment]
> Not a common one, but I think it is a valid one. I've seen devs try this, and it only doesn't really work when there are storage collections in the state. But if everything is in-memory and you just want to return all of the state, there could be a reason to do so.

Makes sense.

I have taken a look at what `ink!` does with `Self` and they just ban its usage in non-constructor functions altogether:
![latest-screenshot](https://user-images.githubusercontent.com/7879134/203930372-d3c76d11-7ad0-4580-a413-90651e7b3da5.png)

So maybe banning all occurrences of `Self` makes more sense from the maintenance point of view.

**Comment by austinabell** [comment]
> So maybe banning all occurrences of Self makes more sense from the maintenance point of view.

My intuition would agree with this. If they _really_ wanted to serialize the state as a return value, they could use the type name explicitly or a number of other ways to work around.

Might be best to nudge devs away from this, as I've noticed a few times devs have accidentally forgotten to mark the fn as `init`
