### ISSUE TITLE
ABI generation fails with lifetimes

### ISSUE THREAD

**Issue by miraclx** [near/near-sdk-rs#974]
Similar to #972.

```rust
#[near_bindgen]
impl MyType {
    pub fn slice<'a>(data: &'a String) -> &'a str { ... }
}
```

```console
$ cargo build --features near-sdk/__abi-generate
   Compiling adder v0.1.0 (/Users/miraclx/git/near/near-sdk-rs/examples/adder)
error[E0261]: use of undeclared lifetime name `'a`
  --> src/lib.rs:3:17
   |
 3 |     pub fn slice<'a>(data: &'a String) -> &'a str {
   |                 -                          ^^ undeclared lifetime
   |                 |
   |                 help: consider introducing lifetime `'a` here: `<'a>`

For more information about this error, try `rustc --explain E0261`.```

**Comment by itegulov** [comment]
Just a note that the existing lifetime support is limited to top-level lifetimes. For example this does not compile:
```rust
pub fn slice<'a>(data: Cow<'a, [u8; 32]>) -> Cow<'a, [u8; 32]> {
    data
}
```

**Comment by miraclx** [comment]
I think lifetimes in argument position is pretty much invalid form. As part of the return type, which is more reasonable, it compiles just fine.

**Comment by itegulov** [comment]
@miraclx 

> I think lifetimes in argument position is pretty much invalid form.

Can you elaborate on why you think it is invalid form? The `foo` example above seems reasonable to me.

**Comment by miraclx** [comment]
Well, really, my thought was: in the context of the code-generated contract API, reference to data that was deserialized just for you doesn't seem very useful. But yeah, the scope extends larger than this. Enough to be generalized, so it could technically be called by another method in the contract that only has a reference to pass to it, so that makes sense. You can ignore the original comment.

But, in that case, we should make an effort to resolve the issue you highlighted in https://github.com/near/near-sdk-rs/issues/974#issuecomment-1330048298.

Two options I've experimented with locally use `TokenStream` sanitization as an alternative to #982, like in #1001;

 - The first approach strips all lifetime patterns from type signatures.
   - `&'a Cow<'b, 'c, [u8; 32]>` -> `&Cow<[u8; 32]>`
 - While the second approach replaces all lifetime patterms with the implicit lifetime.
   - `&'a Cow<'b, 'c, [u8; 32]>` -> `&'_ Cow<'_, '_, [u8; 32]>`

.. both of which are equivalent to the compiler, and are sufficient for ABI generation. I'll submit both PRs for evaluation in a sec.

**Comment by miraclx** [comment]
> But yeah, the scope extends larger than this. Enough to be generalized, so it could technically be called by another method in the contract that only has a reference to pass to it, so that makes sense. You can ignore the original comment.

Honestly, I take that back. I think deserialized inputs to methods of the exported contract API should be received with full ownership. And if you need a method that you can either call from inside the contract or outside of it; you can keep the main impl private and just export a proxy that consumes ownership and passes a reference to the main impl.

We're already doing this implicitly, and it works for the trivial cases, but reconciling a complete solution to this issue with that implementation would be difficult.

This, for example, is how the input deserializer looks from the exported contract API:

```rust
#[serde(Deserialize)]
struct Input {
    other: Cow<'a, [&'b str; 32]>,
}
```

some issues I can point out here are;
 - first, the lifetimes are undeclared so this is invalid
 - second, serde doesn't know how to reconcile lifetimes by default. So every field would need to be annotated with `#[serde(borrow)]`
