### ISSUE TITLE
Use of generics returns a confusing error

### ISSUE THREAD

**Issue by miraclx** [near/near-sdk-rs#979]
We should consider returning a neater error message stating that generics aren't supported, instead of the confusing error it currently returns.

Especially since, it's perfectly valid code without the `#[near_bindgen]` attr.

```rust
#[near_bindgen]
impl MyType {
    pub fn method<T>(arg: T) -> T { ... }
}
```

```console
$ cargo build
   Compiling contract v0.1.0 (/path/to/contract)
error[E0401]: can't use generic parameters from outer function
  --> src/lib.rs:10:28
   |
10 |     pub fn method<T>(data: T) -> T {
   |            ---------       ^ use of generic parameter from outer function
   |            |      |
   |            |      type parameter from outer function
   |            help: try using a local generic parameter instead: `method<T, T>`

For more information about this error, try `rustc --explain E0401`.
error: could not compile `contract` due to previous error
```

But technically, it's clear what the hurdle will be here. It's understandably tricky disambiguating between generic identifiers and explicitly typed ones. Would be interesting to investigate.

**Comment by miraclx** [comment]
One option is to just disable the declaration of generics in public functions altogether. Unsure if there's a use-case for them anyway. I can't personally think of any patterns that require them.

[`impl<N> MyType<N>` already returns `Impl type parameters are not supported for smart contracts.`](https://github.com/near/near-sdk-rs/blob/2d512ebe78b376cf76c85f01dcbe64472bf0a775/near-sdk-macros/src/core_impl/info_extractor/item_impl_info.rs)

**Comment by itegulov** [comment]
Yeah just feels like an oversight to me, opened a quick PR
