### ISSUE TITLE
nix config accidentally committed

### ISSUE THREAD

**Issue by austinabell** [near/near-sdk-rs#984]
in https://github.com/near/near-sdk-rs/pull/977 the nix configs were committed to master but were not reviewed.

This issue tracks either removing it, verifying that this is a generally usable config that's worth keeping, or modifying it so it is.

cc @DavidM-D

**Comment by DavidM-D** [comment]
The root cause of this issue is that I'm a bit of a mug.

This is helpful, because it automatically brings curl into scope which you need to run the FT and NFT contract tests. It isn't helpful because we haven't agreed that nix is how we want to manage dependencies.

I'll remove it

**Comment by austinabell** [comment]
> This is helpful, because it automatically brings curl into scope which you need to run the FT and NFT contract tests. It isn't helpful because we haven't agreed that nix is how we want to manage dependencies.
> 
> I'll remove it

I'm personally open to it, just a bit of a nix boomer myself. Would love input from others on this. I don't have any reason why not

**Comment by DavidM-D** [comment]
So it is a possibility, but this is only half of a nix config, it's a layer on top of a rust dev env flake I have for this project. So I'll remove it first then maybe we can discuss whether this makes sense.

**Comment by ChaoticTempest** [comment]
hmm, how reproducible is Nix? I'm a noob to it, but it seems like it could be cmake all over again, where you just end spending most of your time fine tuning the build system if one of the packages don't work properly for a specific OS or arch. Nothing wrong with that if we can get it right but does sound like a constant maintenance concern
