### ISSUE TITLE
New collections using `FreeList` internally might consume much more gas than using `Vector` depending on use case

### ISSUE THREAD

**Issue by Tarnadas** [near/near-sdk-rs#990]
Hello,

ok so first I'm sorry for the confusingly long title, but I didn't know how else to tell this in a short sentence.
Let me explain my use case:

In my contract I keep track of work that needs to be done, but might not fit into current execution of contract due to gas limitations. Instead I postpone this work into future executions of the contract.
I keep track of this work using the new `store::UnorderedMap`.

I noticed a weird behavior using this new API where gas usage increased when I removed elements from the start while iterating through them. The implementation reveals that internally for iteration a `FreeList` is used which does not re-arrange elements on removal. This is quite bad for my use case, because I need to optimize gas usage for worst case.

In a worst case scenario my `UnorderedMap` will be filled quite heavily in a single contract call. Then in later contract calls this work will be executed. Unfortunately iterating and removing the elements at the start results in the iterator visiting empty elements in successive contract calls. The gas usage increases with every call!

When I switch back to the legacy `UnorderedMap` which internally uses `Vector` (I assume?) for iteration, I no longer have this problem. The gas usage on first iteration is a little more, but it does not increase with every iteration.

Please let me know if I need to explain further and eventually give a code example.

My suggested solution would be to have another `store::UnorderedMap` that also uses `Vector` for storing keys. The user should be able to pick one of both and the difference would need to be explained. Since other collection types also use `FreeList` under the hood these collections would also need a second implementation for consistency reasons.

**Comment by austinabell** [comment]
No need for more context, that makes sense! This was a trade-off that was picked to optimize for gas in most cases, and the case of a large amount of deletions without replacing them _and_ iterating through the elements in a non-view call is the negative side of that trade-off but assumed to be very uncommon. The fact that the "bucket" of keys doesn't re-arrange elements on removal is for the optimization of gas costs.

There was an API I was considering adding when designing this that I think would solve this problem, but I'd love your confirmation:

The basic idea is having some sort of `defrag` method (on `FreeList` but that extends to `UnorderedMap` and others) where it will swap all of the last elements into the empty indices of the `FreeList` (could also be a method that just does this operation once, to give more control). This would mean that it would give you control over when the elements are re-arranged to be more compact for iteration. Would this solve your issue?

Alternatively, we could consider adding a method like `remove_defrag` that is like `remove` except that it does a swap-remove, loads the swapped index node, and writes that back to storage on delete. This on its own doesn't solve all use cases, though, as if someone had deleted a large number of elements already that they won't replace, they would not have the ability to defragment that storage.

WDYT?

**Comment by Tarnadas** [comment]
The `defrag` method would be great! I'm pretty sure it would solve my issue. After thinking a little bit about it, I also think that having another almost identical implementation is probably a really bad idea :D 

I assume the `remove_defrag` would also work, but since `defrag` will be able to do bulk defragging eventually, I would rather use the first option.

My code looks roughly like this:

```rs
        while let Some((id, work_item)) =
            work.iter().next()
        {
            if env::prepaid_gas().0 - env::used_gas().0
                < required_gas
            {
                break;
            }

            // do stuff with `work_item`

            work.remove(&id);
        }
```

**Comment by austinabell** [comment]
Awesome! I think this is a valuable addition. I think this issue might be a good first issue to get entry on the SDK and storage collections, so I'll mark it as such for now, but if it doesn't get picked up, I'll do it when I have a spare cycle because I've already thought it through.

**Comment by askoa** [comment]
I'll pick this up.

**Comment by austinabell** [comment]
> I'll pick this up.

Awesome! Let me know if you'd like more specifics on what this API could/would look like :) Good luck!

**Comment by askoa** [comment]
@austinabell I have created a draft PR with `defrag` function. I am yet to write tests and update the `LookupMap` in `UnorderedMap` with swapped indices. Let me know if this looks okay.

**Comment by austinabell** [comment]
> Edit: There might be a simple solution for `UnorderedMap`. Rather than iterating `keys: FreeList` we can iterate `values: LookupMap`. The `values` store the key and does not have the empty entries issues in `FreeList`. What do you think?

This isn't possible because you cannot iterate over a `LookupMap` because it doesn't track the keys. That's the difference with `UnorderedMap`. I've given some suggestions on the PR, hope they're helpful!

**Comment by austinabell** [comment]
> The underlying `BTreeMap` has an iterator. Can't we expose it in LookupMap?

That only contains the elements that have been loaded in the current execution. It acts as a cache to make the collection lazily loaded, so it doesn't contain all elements needed.
